const products = [
  {
    _id: '422210099',
    name: 'Tinh Chất Estee Lauder Dưỡng Sáng Hồng & Mờ Sạm Nám 50ml',
    category: 'Chăm Sóc Da Mặt / Quy Trình Chăm Sóc Da / Serum / Tinh Chất',
    brand: 'ESTEE LAUDER',
    desc_vn: 'Tinh Chất Estee Lauder Dưỡng Sáng Hồng & Mờ Sạm Nám 50ml',
    desc_eng:
      'Perfectionist Pro Rapid Brightening Treatment with Ferment3 + Vitamin C',
    price: '3870000',
    discount: null,
    old_price: null,
    image:
      'https://media.hasaki.vn/catalog/product/t/o/top_fb_ads_422210099_310523-1685529014_img_380x380_64adc6_fit_center.jpg',
    rating: 4.35,
    rates: 77,
    products_sold: 37,
  },
  {
    _id: '422210100',
    name: 'Phấn Bắt Sáng MAC Màu Beaming Blush 9g',
    category: 'Trang Điểm / Trang Điểm Mặt / Tạo Khối / Highlight',
    brand: 'MAC',
    desc_vn: 'Phấn Bắt Sáng MAC Màu Beaming Blush 9g',
    desc_eng: 'Extra Dimension Skinfinish - Beaming Blush',
    price: '1070000',
    discount: null,
    old_price: null,
    image:
      'https://media.hasaki.vn/catalog/product/t/o/top_fb_ads_422210100_310523-1685529195_img_380x380_64adc6_fit_center.jpg',
    rating: 4.27,
    rates: 128,
    products_sold: 76,
  },
  {
    _id: '422209988',
    name: 'Son Môi Lancôme Mịn Lì Mềm Mịn #278 Hồng Đất 3.4g',
    category: 'Trang Điểm / Trang Điểm Môi / Son Thỏi',
    brand: 'LANCÔME',
    desc_vn: 'Son Môi Lancôme Mịn Lì Mềm Mịn #278 Hồng Đất 3.4g',
    desc_eng: "L'Absolu Rouge Intimatte Lipstick #278 Hide And Seek",
    price: '900000',
    discount: '9%',
    old_price: '990000',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping_422209988-1678358605_img_380x380_64adc6_fit_center.jpg',
    rating: 4.08,
    rates: 72,
    products_sold: 37,
  },
  {
    _id: '422209987',
    name: 'Son Môi Lancôme Mịn Lì Lâu Trôi #196 Cam Cháy 3.4g',
    category: 'Trang Điểm / Trang Điểm Môi / Son Thỏi',
    brand: 'LANCÔME',
    desc_vn: 'Son Môi Lancôme Mịn Lì Lâu Trôi #196 Cam Cháy 3.4g',
    desc_eng: "L'Absolu Rouge Drama Matte Lipstick #196 French Touch",
    price: '900000',
    discount: '9%',
    old_price: '990000',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping_422209987-1678358635_img_380x380_64adc6_fit_center.jpg',
    rating: 4.35,
    rates: 34,
    products_sold: '1',
  },
  {
    _id: '422209365',
    name: 'Son Lì Shu Uemura Có Dưỡng Kinu Satin BG964 3.3g',
    category: 'Trang Điểm / Trang Điểm Môi / Son Thỏi',
    brand: 'SHU UEMURA',
    desc_vn: 'Son Lì Shu Uemura Có Dưỡng Kinu Satin BG964 3.3g',
    desc_eng: 'Rouge Unlimited Kinu Satin BG964',
    price: '722000',
    discount: '15%',
    old_price: '850000',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-son-li-shu-uemura-co-duong-kinu-satin-bg964-3-3g-1664953042_img_380x380_64adc6_fit_center.jpg',
    rating: 4.03,
    rates: 141,
    products_sold: 114,
  },
  {
    _id: '422209364',
    name: 'Son Lì Shu Uemura Có Dưỡng Kinu Satin BG963 3.3g',
    category: 'Trang Điểm / Trang Điểm Môi / Son Thỏi',
    brand: 'SHU UEMURA',
    desc_vn: 'Son Lì Shu Uemura Có Dưỡng Kinu Satin BG963 3.3g',
    desc_eng: 'Rouge Unlimited Kinu Satin BG963',
    price: '722000',
    discount: '15%',
    old_price: '850000',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-son-li-shu-uemura-co-duong-kinu-satin-bg963-3-3g-1664953707_img_380x380_64adc6_fit_center.jpg',
    rating: 4.07,
    rates: 49,
    products_sold: 106,
  },
  {
    _id: '422209370',
    name: 'Son Môi Lancôme Mịn Lì Mềm Mịn #888 Đỏ Mận 3.4g',
    category: 'Trang Điểm / Trang Điểm Môi / Son Thỏi',
    brand: 'LANCÔME',
    desc_vn: 'Son Môi Lancôme Mịn Lì Mềm Mịn #888 Đỏ Mận 3.4g',
    desc_eng: "L'Absolu Rouge Intimatte Lipstick #888 Kind Of Sexy",
    price: '751000',
    discount: '24%',
    old_price: '990000',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping_422209370-1678358576_img_380x380_64adc6_fit_center.jpg',
    rating: 4.59,
    rates: 93,
    products_sold: '1',
  },
  {
    _id: '422209371',
    name: 'Son Môi Lancôme Mịn Lì Mềm Mịn #525 Hồng Mận 3.4g',
    category: 'Trang Điểm / Trang Điểm Môi / Son Thỏi',
    brand: 'LANCÔME',
    desc_vn: 'Son Môi Lancôme Mịn Lì Mềm Mịn #525 Hồng Mận 3.4g',
    desc_eng: "L'Absolu Rouge Intimatte Lipstick #525 Sexy Cherry",
    price: '751000',
    discount: '24%',
    old_price: '990000',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping_422209371-1678358472_img_380x380_64adc6_fit_center.jpg',
    rating: 4.6,
    rates: 115,
    products_sold: '1',
  },
  {
    _id: '422209621',
    name: 'Sáp Tẩy Trang Clinique 30ml',
    category:
      'Chăm Sóc Da Mặt / Quy Trình Chăm Sóc Da / Tẩy Trang / Tẩy Trang Mặt',
    brand: 'CLINIQUE',
    desc_vn: 'Sáp Tẩy Trang Clinique 30ml',
    desc_eng: 'Take The Day Off Cleansing Balm',
    price: '220000',
    discount: null,
    old_price: null,
    image:
      'https://media.hasaki.vn/catalog/product/t/o/top_fb_ads_422209621_310523-1685529759_img_380x380_64adc6_fit_center.jpg',
    rating: 4.74,
    rates: 137,
    products_sold: 141,
  },
  {
    _id: '422209507',
    name: 'Tinh Chất Estee Lauder Phục Hồi Ngăn Ngừa Lão Hóa 30ml',
    category: 'Chăm Sóc Da Mặt / Quy Trình Chăm Sóc Da / Serum / Tinh Chất',
    brand: 'ESTEE LAUDER',
    desc_vn: 'Tinh Chất Estee Lauder Phục Hồi Ngăn Ngừa Lão Hóa 30ml',
    desc_eng: 'Advanced Night Repair Synchronized Multi-Recovery',
    price: '2700000',
    discount: null,
    old_price: null,
    image:
      'https://media.hasaki.vn/catalog/product/t/o/top_fb_ads_422209507_300523-1685442221_img_380x380_64adc6_fit_center.jpg',
    rating: 4.84,
    rates: 100,
    products_sold: 65,
  },
  {
    _id: '422209510',
    name: 'Nước Dưỡng Tinh Chất Estee Lauder Kích Hoạt Làn Da 100ml',
    category: 'Chăm Sóc Da Mặt / Quy Trình Chăm Sóc Da / Lotion / Sữa Dưỡng',
    brand: 'ESTEE LAUDER',
    desc_vn: 'Nước Dưỡng Tinh Chất Estee Lauder Kích Hoạt Làn Da 100ml',
    desc_eng: 'Micro Essence Treatment Lotion with Bio-Ferment',
    price: '2200000',
    discount: null,
    old_price: null,
    image:
      'https://media.hasaki.vn/catalog/product/t/o/top_fb_ads_422209510_300523-1685442280_img_380x380_64adc6_fit_center.jpg',
    rating: 4.08,
    rates: 54,
    products_sold: 131,
  },
  {
    _id: '422209511',
    name: 'Tinh Chất Estee Lauder Phục Hồi Ngăn Ngừa Lão Hóa 50ml',
    category: 'Chăm Sóc Da Mặt / Quy Trình Chăm Sóc Da / Serum / Tinh Chất',
    brand: 'ESTEE LAUDER',
    desc_vn: 'Tinh Chất Estee Lauder Phục Hồi Ngăn Ngừa Lão Hóa 50ml',
    desc_eng: 'Advanced Night Repair Synchronized Multi-Recovery',
    price: '3700000',
    discount: null,
    old_price: null,
    image:
      'https://media.hasaki.vn/catalog/product/t/o/top_fb_ads_422209511_310523-1685528937_img_380x380_64adc6_fit_center.jpg',
    rating: 4.04,
    rates: 107,
    products_sold: 76,
  },
  {
    _id: '422209512',
    name: 'Tinh Chất Estee Lauder Phục Hồi Ngăn Ngừa Lão Hóa 75ml',
    category: 'Chăm Sóc Da Mặt / Quy Trình Chăm Sóc Da / Serum / Tinh Chất',
    brand: 'ESTEE LAUDER',
    desc_vn: 'Tinh Chất Estee Lauder Phục Hồi Ngăn Ngừa Lão Hóa 75ml',
    desc_eng: 'Advanced Night Repair Synchronized Multi-Recovery',
    price: '4600000',
    discount: null,
    old_price: null,
    image:
      'https://media.hasaki.vn/catalog/product/t/o/top_fb_ads_422209512_310523-1685528969_img_380x380_64adc6_fit_center.jpg',
    rating: 4.71,
    rates: 78,
    products_sold: 106,
  },
  {
    _id: '422209513',
    name: 'Kem Dưỡng Estee Lauder Collagen Ngăn Ngừa Lão Hóa 50ml',
    category: 'Chăm Sóc Da Mặt / Quy Trình Chăm Sóc Da / Kem Dưỡng / Dầu Dưỡng',
    brand: 'ESTEE LAUDER',
    desc_vn: 'Kem Dưỡng Estee Lauder Collagen Ngăn Ngừa Lão Hóa 50ml',
    desc_eng: 'Revitalizing Supreme+ Youth Power Creme Moisturizer',
    price: '3200000',
    discount: null,
    old_price: null,
    image:
      'https://media.hasaki.vn/catalog/product/t/o/top_fb_ads_422209513_300523-1685442322_img_380x380_64adc6_fit_center.jpg',
    rating: 4.28,
    rates: 78,
    products_sold: 44,
  },
  {
    _id: '422209514',
    name: 'Kem Dưỡng Clinique Cấp Ẩm Chuyên Sâu 50ml',
    category: 'Chăm Sóc Da Mặt / Quy Trình Chăm Sóc Da / Kem Dưỡng / Dầu Dưỡng',
    brand: 'CLINIQUE',
    desc_vn: 'Kem Dưỡng Clinique Cấp Ẩm Chuyên Sâu 50ml',
    desc_eng: 'Moisture Surge 100H Auto-Replenishing Hydrator',
    price: '1460000',
    discount: null,
    old_price: null,
    image:
      'https://media.hasaki.vn/catalog/product/t/o/top_fb_ads_422209514_310523-1685529768_img_380x380_64adc6_fit_center.jpg',
    rating: 4.02,
    rates: 98,
    products_sold: 90,
  },
  {
    _id: '422209525',
    name: 'Kem Dưỡng Clinique Cấp Ẩm Chuyên Sâu 30ml',
    category: 'Chăm Sóc Da Mặt / Quy Trình Chăm Sóc Da / Kem Dưỡng / Dầu Dưỡng',
    brand: 'CLINIQUE',
    desc_vn: 'Kem Dưỡng Clinique Cấp Ẩm Chuyên Sâu 30ml',
    desc_eng: 'Moisture Surge 100H Auto-Replenishing Hydrator',
    price: '920000',
    discount: null,
    old_price: null,
    image:
      'https://media.hasaki.vn/catalog/product/t/o/top_fb_ads_422209525_310523-1685529778_img_380x380_64adc6_fit_center.jpg',
    rating: 4.55,
    rates: 43,
    products_sold: 146,
  },
  {
    _id: '422209526',
    name: 'Kem Dưỡng Clinique Cấp Ẩm Chuyên Sâu 75ml',
    category: 'Chăm Sóc Da Mặt / Quy Trình Chăm Sóc Da / Kem Dưỡng / Dầu Dưỡng',
    brand: 'CLINIQUE',
    desc_vn: 'Kem Dưỡng Clinique Cấp Ẩm Chuyên Sâu 75ml',
    desc_eng: 'Moisture Surge 100H Auto-Replenishing Hydrator',
    price: '1940000',
    discount: null,
    old_price: null,
    image:
      'https://media.hasaki.vn/catalog/product/t/o/top_fb_ads_422209526_310523-1685529789_img_380x380_64adc6_fit_center.jpg',
    rating: 4.39,
    rates: 106,
    products_sold: 129,
  },
  {
    _id: '422209527',
    name: 'Kem Dưỡng Clinique Cấp Ẩm Chuyên Sâu 15ml',
    category: 'Chăm Sóc Da Mặt / Quy Trình Chăm Sóc Da / Kem Dưỡng / Dầu Dưỡng',
    brand: 'CLINIQUE',
    desc_vn: 'Kem Dưỡng Clinique Cấp Ẩm Chuyên Sâu 15ml',
    desc_eng: 'Moisture Surge 100H Auto-Replenishing Hydrator',
    price: '490000',
    discount: null,
    old_price: null,
    image:
      'https://media.hasaki.vn/catalog/product/t/o/top_fb_ads_422209527_310523-1685529797_img_380x380_64adc6_fit_center.jpg',
    rating: 4.01,
    rates: 137,
    products_sold: 63,
  },
  {
    _id: '422209529',
    name: 'Phấn Bắt Sáng MAC Màu Show Gold 9g',
    category: 'Trang Điểm / Trang Điểm Mặt / Tạo Khối / Highlight',
    brand: 'MAC',
    desc_vn: 'Phấn Bắt Sáng MAC Màu Show Gold 9g',
    desc_eng: 'Extra Dimension Skinfinish - Show Gold',
    price: '1070000',
    discount: null,
    old_price: null,
    image:
      'https://media.hasaki.vn/catalog/product/t/o/top_fb_ads_422209529_310523-1685529211_img_380x380_64adc6_fit_center.jpg',
    rating: 4.16,
    rates: 145,
    products_sold: 49,
  },
  {
    _id: '422209530',
    name: 'Son Thỏi MAC Mịn Lì Nhẹ Môi 935 Ruby New - Đỏ Thuần 3g',
    category: 'Trang Điểm / Trang Điểm Môi / Son Thỏi',
    brand: 'MAC',
    desc_vn: 'Son Thỏi MAC Mịn Lì Nhẹ Môi 935 Ruby New - Đỏ Thuần 3g',
    desc_eng: 'Powder Kiss Lipstick',
    price: '710000',
    discount: null,
    old_price: null,
    image:
      'https://media.hasaki.vn/catalog/product/t/o/top_fb_ads_422209530_310523-1685529223_img_380x380_64adc6_fit_center.jpg',
    rating: 4.06,
    rates: 58,
    products_sold: 105,
  },
  {
    _id: '422209531',
    name: 'Son Kem MAC 989 Mull It Over - Cam Hồng Đất 5ml',
    category: 'Trang Điểm / Trang Điểm Môi / Son Kem / Tint',
    brand: 'MAC',
    desc_vn: 'Son Kem MAC 989 Mull It Over - Cam Hồng Đất 5ml',
    desc_eng: 'Powder Kiss Liquid Lipcolour',
    price: '830000',
    discount: null,
    old_price: null,
    image:
      'https://media.hasaki.vn/catalog/product/t/o/top_fb_ads_422209531_310523-1685530985_img_380x380_64adc6_fit_center.jpg',
    rating: 4.91,
    rates: 88,
    products_sold: 65,
  },
  {
    _id: '422209533',
    name: 'Son Kem MAC 996 Date-Maker - Hồng Da 5ml',
    category: 'Trang Điểm / Trang Điểm Môi / Son Kem / Tint',
    brand: 'MAC',
    desc_vn: 'Son Kem MAC 996 Date-Maker - Hồng Da 5ml',
    desc_eng: 'Powder Kiss Liquid Lipcolour',
    price: '830000',
    discount: null,
    old_price: null,
    image:
      'https://media.hasaki.vn/catalog/product/t/o/top_fb_ads_422209533_310523-1685529266_img_380x380_64adc6_fit_center.jpg',
    rating: 4.1,
    rates: 90,
    products_sold: 75,
  },
  {
    _id: '422209534',
    name: 'Son Kem MAC 997 Over The Taupe - Nâu Tây 5ml',
    category: 'Trang Điểm / Trang Điểm Môi / Son Kem / Tint',
    brand: 'MAC',
    desc_vn: 'Son Kem MAC 997 Over The Taupe - Nâu Tây 5ml',
    desc_eng: 'Powder Kiss Liquid Lipcolour',
    price: '830000',
    discount: null,
    old_price: null,
    image:
      'https://media.hasaki.vn/catalog/product/t/o/top_fb_ads_422209534_310523-1685529276_img_380x380_64adc6_fit_center.jpg',
    rating: 4.24,
    rates: 114,
    products_sold: 58,
  },
  {
    _id: '422209535',
    name: 'Son Kem MAC 995 Fashion, Sweetie - Đỏ Trầm 5ml',
    category: 'Trang Điểm / Trang Điểm Môi / Son Kem / Tint',
    brand: 'MAC',
    desc_vn: 'Son Kem MAC 995 Fashion, Sweetie - Đỏ Trầm 5ml',
    desc_eng: 'Powder Kiss Liquid Lipcolour',
    price: '830000',
    discount: null,
    old_price: null,
    image:
      'https://media.hasaki.vn/catalog/product/t/o/top_fb_ads_422209535_310523-1685529293_img_380x380_64adc6_fit_center.jpg',
    rating: 4.06,
    rates: 35,
    products_sold: 137,
  },
  {
    _id: '422209536',
    name: 'Son Kem MAC 979 Impulsive - Cam Đào 5ml',
    category: 'Trang Điểm / Trang Điểm Môi / Son Kem / Tint',
    brand: 'MAC',
    desc_vn: 'Son Kem MAC 979 Impulsive - Cam Đào 5ml',
    desc_eng: 'Powder Kiss Liquid Lipcolour',
    price: '830000',
    discount: null,
    old_price: null,
    image:
      'https://media.hasaki.vn/catalog/product/t/o/top_fb_ads_422209536_310523-1685529313_img_380x380_64adc6_fit_center.jpg',
    rating: 4.1,
    rates: 137,
    products_sold: 73,
  },
  {
    _id: '422209506',
    name: 'Kem Dưỡng Mắt Estee Lauder Dạng Gel Giảm Quầng Thâm 15ml',
    category:
      'Chăm Sóc Da Mặt / Quy Trình Chăm Sóc Da / Chăm Sóc Vùng Da Mắt / Serum / Kem Dưỡng Mắt',
    brand: 'ESTEE LAUDER',
    desc_vn: 'Kem Dưỡng Mắt Estee Lauder Dạng Gel Giảm Quầng Thâm 15ml',
    desc_eng:
      'Advanced Night Repair Eye Supercharged Gel-Crème Synchronized Multi-Recovery',
    price: '2250000',
    discount: null,
    old_price: null,
    image:
      'https://media.hasaki.vn/catalog/product/t/o/top_fb_ads_422209506_300523-1685442471_img_380x380_64adc6_fit_center.jpg',
    rating: 4.87,
    rates: 99,
    products_sold: 37,
  },
  {
    _id: '422209119',
    name: '[Mini] Kem Dưỡng Ẩm Laneige Dành Cho Da Dầu Và Da Hỗn Hợp 10ml',
    category: 'Chăm Sóc Da Mặt / Phụ Kiện Chăm Sóc Da / Mini / Sample',
    brand: 'LANEIGE',
    desc_vn: '[Mini] Kem Dưỡng Ẩm Laneige Dành Cho Da Dầu Và Da Hỗn Hợp 10ml',
    desc_eng: 'Water Bank Blue HA Cream Oily',
    price: '200000',
    discount: null,
    old_price: null,
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-kem-duong-am-laneige-danh-cho-da-dau-va-da-hon-hop-10ml-1661329619_img_380x380_64adc6_fit_center.jpg',
    rating: 4.13,
    rates: 61,
    products_sold: 37,
  },
  {
    _id: '422208832',
    name: '[Mini] Serum Laneige Cao Cấp Thúc Đẩy Dưỡng Sáng Da 15ml',
    category: 'Chăm Sóc Da Mặt / Phụ Kiện Chăm Sóc Da / Mini / Sample',
    brand: 'LANEIGE',
    desc_vn: '[Mini] Serum Laneige Cao Cấp Thúc Đẩy Dưỡng Sáng Da 15ml',
    desc_eng: 'Radian-C Advanced Effector',
    price: '105000',
    discount: null,
    old_price: null,
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-mini-tinh-chat-laneige-duong-sang-da-mo-tham-nam-15ml-1658546250_img_380x380_64adc6_fit_center.jpg',
    rating: 4.39,
    rates: 139,
    products_sold: '7',
  },
  {
    _id: '422207881',
    name: 'Kem Chống Nắng Laneige Radian-C Dưỡng Sáng Da 50ml',
    category: 'Chăm Sóc Da Mặt / Quy Trình Chăm Sóc Da / Chống Nắng Da Mặt',
    brand: 'LANEIGE',
    desc_vn: 'Kem Chống Nắng Laneige Radian-C Dưỡng Sáng Da 50ml',
    desc_eng: 'Radian-C Sun Cream SPF 50+ PA++++',
    price: '525000',
    discount: '25%',
    old_price: '700000',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-kem-chong-nang-laneige-radian-c-duong-sang-da-50ml-1676625250_img_380x380_64adc6_fit_center.jpg',
    rating: 4.52,
    rates: 139,
    products_sold: '4',
  },
  {
    _id: '422207880',
    name: 'Serum Laneige Cao Cấp Thúc Đẩy Dưỡng Sáng Da 150ml',
    category: 'Chăm Sóc Da Mặt / Quy Trình Chăm Sóc Da / Serum / Tinh Chất',
    brand: 'LANEIGE',
    desc_vn: 'Serum Laneige Cao Cấp Thúc Đẩy Dưỡng Sáng Da 150ml',
    desc_eng: 'Radian-C Advanced Effector',
    price: '923000',
    discount: '12%',
    old_price: '1050000',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-tinh-chat-laneige-cao-cap-thuc-day-duong-sang-da-150ml-1654845418_img_380x380_64adc6_fit_center.jpg',
    rating: 4.58,
    rates: 40,
    products_sold: '1',
  },
  {
    _id: '422207654',
    name: 'Bộ Sản Phẩm Laneige Dưỡng Ẩm Cho Da Thường Đến Khô 5 Món',
    category:
      'Chăm Sóc Da Mặt / Quy Trình Chăm Sóc Da / Bộ Sản Phẩm Chăm Sóc Da',
    brand: 'LANEIGE',
    desc_vn: 'Bộ Sản Phẩm Laneige Dưỡng Ẩm Cho Da Thường Đến Khô 5 Món',
    desc_eng: 'Water Bank Blue HA 5 Step Essential Kit - Normal to Dry skin',
    price: '239000',
    discount: '33%',
    old_price: '355000',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-bo-san-pham-laneige-duong-am-cho-da-thuong-den-kho-5-mon-1652693564_img_380x380_64adc6_fit_center.jpg',
    rating: 4.49,
    rates: 123,
    products_sold: 98,
  },
  {
    _id: '422207343',
    name: 'Kem Dưỡng Ẩm Laneige Dành Cho Da Thường Và Da Khô 50ml',
    category: 'Chăm Sóc Da Mặt / Quy Trình Chăm Sóc Da / Kem Dưỡng / Dầu Dưỡng',
    brand: 'LANEIGE',
    desc_vn: 'Kem Dưỡng Ẩm Laneige Dành Cho Da Thường Và Da Khô 50ml',
    desc_eng: 'Water Bank Blue HA Cream Dry',
    price: '798000',
    discount: '20%',
    old_price: '1000000',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-kem-duong-am-laneige-danh-cho-da-thuong-va-da-kho-50ml-1650681664_img_380x380_64adc6_fit_center.jpg',
    rating: 4.07,
    rates: 123,
    products_sold: '8',
  },
  {
    _id: '422207342',
    name: 'Toner Laneige Dưỡng Ẩm Cho Da Dầu Và Hỗn Hợp 160ml',
    category: 'Chăm Sóc Da Mặt / Quy Trình Chăm Sóc Da / Toner',
    brand: 'LANEIGE',
    desc_vn: 'Toner Laneige Dưỡng Ẩm Cho Da Dầu Và Hỗn Hợp 160ml',
    desc_eng: 'Water Bank Blue HA Toner Oily',
    price: '692000',
    discount: '10%',
    old_price: '770000',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-nuoc-can-bang-laneige-duong-am-cho-da-dau-va-hon-hop-160ml-1650683017_img_380x380_64adc6_fit_center.jpg',
    rating: 4.73,
    rates: 34,
    products_sold: '3',
  },
  {
    _id: '422207341',
    name: 'Tinh Chất Laneige Dưỡng Ẩm, Phục Hồi Da 50ml',
    category: 'Chăm Sóc Da Mặt / Quy Trình Chăm Sóc Da / Serum / Tinh Chất',
    brand: 'LANEIGE',
    desc_vn: 'Tinh Chất Laneige Dưỡng Ẩm, Phục Hồi Da 50ml',
    desc_eng: 'Water Bank Blue HA Serum',
    price: '979000',
    discount: '18%',
    old_price: '1200000',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-tinh-chat-laneige-duong-am-phuc-hoi-da-50ml-1650687156_img_380x380_64adc6_fit_center.jpg',
    rating: 4.74,
    rates: 138,
    products_sold: 56,
  },
  {
    _id: '422207339',
    name: 'Kem Dưỡng Ẩm Laneige Dành Cho Da Dầu Và Da Hỗn Hợp 50ml',
    category: 'Chăm Sóc Da Mặt / Quy Trình Chăm Sóc Da / Kem Dưỡng / Dầu Dưỡng',
    brand: 'LANEIGE',
    desc_vn: 'Kem Dưỡng Ẩm Laneige Dành Cho Da Dầu Và Da Hỗn Hợp 50ml',
    desc_eng: 'Water Bank Blue HA Cream Oily',
    price: '790000',
    discount: '21%',
    old_price: '1000000',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-kem-duong-am-laneige-danh-cho-da-dau-va-da-hon-hop-50ml-1-1650853833_img_380x380_64adc6_fit_center.jpg',
    rating: 4.96,
    rates: 127,
    products_sold: '11',
  },
  {
    _id: '422207337',
    name: 'Sữa Dưỡng Ẩm Laneige Dành Cho Da Thường Và Da Khô 120ml',
    category: 'Chăm Sóc Da Mặt / Quy Trình Chăm Sóc Da / Lotion / Sữa Dưỡng',
    brand: 'LANEIGE',
    desc_vn: 'Sữa Dưỡng Ẩm Laneige Dành Cho Da Thường Và Da Khô 120ml',
    desc_eng: 'Water Bank Blue HA Emulsion Dry',
    price: '749000',
    discount: '9%',
    old_price: '820000',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-sua-duong-am-laneige-danh-cho-da-thuong-va-da-kho-120ml-1650851835_img_380x380_64adc6_fit_center.jpg',
    rating: 4.21,
    rates: 75,
    products_sold: 62,
  },
  {
    _id: '422207336',
    name: 'Toner Laneige Dưỡng Ẩm Cho Da Thường Và Khô 160ml',
    category: 'Chăm Sóc Da Mặt / Quy Trình Chăm Sóc Da / Toner',
    brand: 'LANEIGE',
    desc_vn: 'Toner Laneige Dưỡng Ẩm Cho Da Thường Và Khô 160ml',
    desc_eng: 'Water Bank Blue HA Toner Dry',
    price: '652000',
    discount: '15%',
    old_price: '770000',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-nuoc-can-bang-laneige-duong-am-cho-da-thuong-va-kho-160ml-1650685549_img_380x380_64adc6_fit_center.jpg',
    rating: 4.26,
    rates: 50,
    products_sold: 119,
  },
  {
    _id: '422207307',
    name: 'Son Môi Lancôme Mịn Lì Mềm Mịn #274 Hồng Trà Sữa 3.4g',
    category: 'Trang Điểm / Trang Điểm Môi / Son Thỏi',
    brand: 'LANCÔME',
    desc_vn: 'Son Môi Lancôme Mịn Lì Mềm Mịn #274 Hồng Trà Sữa 3.4g',
    desc_eng: "L'Absolu Rouge Intimatte Lipstick #274 Killing Me Softly",
    price: '900000',
    discount: '9%',
    old_price: '990000',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping_422207307-1678358436_img_380x380_64adc6_fit_center.jpg',
    rating: 4.71,
    rates: 58,
    products_sold: 75,
  },
  {
    _id: '422207306',
    name: 'Son Môi Lancôme Mịn Lì Mềm Mịn #196 Cam Cháy 3.4g',
    category: 'Trang Điểm / Trang Điểm Môi / Son Thỏi',
    brand: 'LANCÔME',
    desc_vn: 'Son Môi Lancôme Mịn Lì Mềm Mịn #196 Cam Cháy 3.4g',
    desc_eng: "L'Absolu Rouge Intimatte Lipstick #196 Pleasure First",
    price: '900000',
    discount: '9%',
    old_price: '990000',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping_422207306-1678358354_img_380x380_64adc6_fit_center.jpg',
    rating: 4.55,
    rates: 98,
    products_sold: 51,
  },
  {
    _id: '422207157',
    name: 'Phấn Nước Laneige Cho Lớp Nền Căng Bóng Tự Nhiên 24H #21N 15g',
    category: 'Trang Điểm / Trang Điểm Mặt / Phấn Nước Cushion',
    brand: 'LANEIGE',
    desc_vn: 'Phấn Nước Laneige Cho Lớp Nền Căng Bóng Tự Nhiên 24H #21N 15g',
    desc_eng: 'Neo Cushion Glow 21N',
    price: '549000',
    discount: '13%',
    old_price: '630000',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-phan-nuoc-laneige-cang-bong-24h-tong-mau-21n-15g-1649064787_img_380x380_64adc6_fit_center.jpg',
    rating: 4.2,
    rates: 80,
    products_sold: '25',
  },

  {
    _id: '207500007',
    name: 'Combo 3 Bông Tẩy Trang Silcot Cơ Bản 82 Miếng/Hộp',
    category: 'Trang Điểm / Dụng Cụ Trang Điểm / Bông Tẩy Trang',
    brand: 'SILCOT',
    desc_vn: 'Combo 3 Bông Tẩy Trang Silcot Cơ Bản 82 Miếng/Hộp',
    desc_eng: 'Silcot Velvety Touch Cotton',
    price: 104000,
    old_price: 117000,
    discount: '11%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-bo-3-hop-bong-tay-trang-co-ban-silcot-82-mieng-hop-1684396744_img_380x380_64adc6_fit_center.jpg',
    rating: 4.05,
    rates: 108,
    products_sold: '1.756',
  },
  {
    _id: '422203776',
    name: 'Combo 4 Bông Tẩy Trang Ipek 150 Miếng',
    category: 'Trang Điểm / Dụng Cụ Trang Điểm / Bông Tẩy Trang',
    brand: 'Ipek Klasik',
    desc_vn: 'Combo 4 Bông Tẩy Trang Ipek 150 Miếng',
    desc_eng: 'Cotton Pads',
    price: 109000,
    old_price: 200000,
    discount: '45%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-combo-4-bong-tay-trang-ipek-150-mieng_img_380x380_64adc6_fit_center.jpg',
    rating: 4.13,
    rates: 64,
    products_sold: '1.387',
  },
  {
    _id: '243300007',
    name: 'Bông Tẩy Trang Ipek 150 Miếng',
    category: 'Trang Điểm / Dụng Cụ Trang Điểm / Bông Tẩy Trang',
    brand: 'Ipek Klasik',
    desc_vn: 'Bông Tẩy Trang Ipek 150 Miếng',
    desc_eng: 'Cotton Pads',
    price: 27000,
    old_price: 43000,
    discount: '37%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-bong-tay-trang-ipek-150-mieng_img_380x380_64adc6_fit_center.jpg',
    rating: 4.12,
    rates: 128,
    products_sold: '4.776',
  },
  {
    _id: '422203301',
    name: 'Bông Tẩy Trang Mihoo Kokimi Bông Vuông Túi 240 miếng',
    category: 'Trang Điểm / Dụng Cụ Trang Điểm / Bông Tẩy Trang',
    brand: 'MIHOO',
    desc_vn: 'Bông Tẩy Trang Mihoo Kokimi Bông Vuông Túi 240 miếng',
    desc_eng: 'Cotton Pads Jumpo Size 200+40',
    price: 47000,
    old_price: 55000,
    discount: '15%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-bong-tay-trang-mihoo-kokimi-bong-vuong-tui-240-mieng_img_380x380_64adc6_fit_center.jpg',
    rating: 4.26,
    rates: 120,
    products_sold: '2.340',
  },
  {
    _id: '232100001',
    name: 'Son Dưỡng Môi DHC Không Màu Hỗ Trợ Giảm Thâm Môi 1.5g',
    category: 'Trang Điểm / Trang Điểm Môi / Son Dưỡng Môi',
    brand: 'DHC',
    desc_vn: 'Son Dưỡng Môi DHC Không Màu Hỗ Trợ Giảm Thâm Môi 1.5g',
    desc_eng: 'Lip Cream',
    price: 165000,
    old_price: 199000,
    discount: '17%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-son-duong-moi-khong-mau-dhc-ho-tro-giam-tham-moi-1-5g_h6gVS5btDbZuMLTo_img_380x380_64adc6_fit_center.png',
    rating: 4.91,
    rates: 125,
    products_sold: '496',
  },
  {
    _id: '422203807',
    name: 'Combo 2 Bông Tẩy Trang Ipek 150 Miếng',
    category: 'Trang Điểm / Dụng Cụ Trang Điểm / Bông Tẩy Trang',
    brand: 'Ipek Klasik',
    desc_vn: 'Combo 2 Bông Tẩy Trang Ipek 150 Miếng',
    desc_eng: 'Cotton Pads',
    price: 56000,
    old_price: 100000,
    discount: '44%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-combo-2-bong-tay-trang-ipek-150-mieng_img_380x380_64adc6_fit_center.jpg',
    rating: 4.09,
    rates: 70,
    products_sold: '1.304',
  },
  {
    _id: '422209138',
    name: 'Phấn Phủ innisfree Kiềm Dầu Dạng Bột Khoáng 5g',
    category: 'Trang Điểm / Trang Điểm Mặt / Phấn Phủ',
    brand: 'innisfree',
    desc_vn: 'Phấn Phủ innisfree Kiềm Dầu Dạng Bột Khoáng 5g',
    desc_eng: 'No Sebum Mineral Powder',
    price: 150000,
    old_price: null,
    discount: null,
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-phan-phu-innisfree-kiem-dau-dang-bot-khoang-5g_UirFzkdZW5oWDEfH_img_380x380_64adc6_fit_center.png',
    rating: 4.01,
    rates: 57,
    products_sold: '482',
  },
  {
    _id: '234300029',
    name: 'Son Dưỡng Môi Mediheal Ban Ngày Màu Hồng 10ml',
    category: 'Trang Điểm / Trang Điểm Môi / Son Dưỡng Môi',
    brand: 'MEDIHEAL',
    desc_vn: 'Son Dưỡng Môi Mediheal Ban Ngày Màu Hồng 10ml',
    desc_eng: 'Labocare Pantenolips Healssence',
    price: 59000,
    old_price: 143000,
    discount: '59%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-son-duong-mediheal-ho-tro-giam-tham-lam-hong-moi-ban-ngay-10ml-1681273198_img_380x380_64adc6_fit_center.jpg',
    rating: 4.5,
    rates: 122,
    products_sold: '1.185',
  },
  {
    _id: '422207383',
    name: 'Bút Kẻ Mắt Nước Maybelline Sắc Mảnh BK1 Đen Sắc Sảo 0.4g',
    category: 'Trang Điểm / Trang Điểm Mắt / Kẻ Mắt',
    brand: 'MAYBELLINE',
    desc_vn: 'Bút Kẻ Mắt Nước Maybelline Sắc Mảnh BK1 Đen Sắc Sảo 0.4g',
    desc_eng: 'Hyper Sharp Liner Extreme #BK-1 Ultra Black',
    price: 164000,
    old_price: 218000,
    discount: '25%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-but-ke-mat-nuoc-maybelline-sac-manh-bk1-ultra-black-0-4g_DA9U9N2KrTU5LLJP_img_380x380_64adc6_fit_center.png',
    rating: 4.43,
    rates: 71,
    products_sold: '415',
  },
  {
    _id: '217300001',
    name: 'Bông Tẩy Trang Jomi 120 Miếng',
    category: 'Trang Điểm / Dụng Cụ Trang Điểm / Bông Tẩy Trang',
    brand: 'JOMI',
    desc_vn: 'Bông Tẩy Trang Jomi 120 Miếng',
    desc_eng: 'Cotton Pad',
    price: 28000,
    old_price: 37000,
    discount: '24%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-bong-tay-trang-jomi-120-mieng_img_380x380_64adc6_fit_center.jpg',
    rating: 4.18,
    rates: 96,
    products_sold: '2.420',
  },
  {
    _id: '422206346',
    name: 'Chuốt Mi Browit Kéo Dài Và Cong Mi Dạng Đầu Lược 5.5g',
    category: 'Trang Điểm / Trang Điểm Mắt / Mascara',
    brand: 'Browit',
    desc_vn: 'Chuốt Mi Browit Kéo Dài Và Cong Mi Dạng Đầu Lược 5.5g',
    desc_eng: 'My Everyday Mascara #Endless Night',
    price: 99000,
    old_price: 149000,
    discount: '34%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-chuot-mi-browit-keo-dai-va-cong-mi-dang-dau-luoc-5-5g_JkvSDKxvXSmxH8bx_img_380x380_64adc6_fit_center.png',
    rating: 4.35,
    rates: 35,
    products_sold: '630',
  },
  {
    _id: '100540031',
    name: 'Sáp Dưỡng Môi Vaseline Hồng Xinh 7g',
    category: 'Trang Điểm / Trang Điểm Môi / Son Dưỡng Môi',
    brand: 'VASELINE',
    desc_vn: 'Sáp Dưỡng Môi Vaseline Hồng Xinh 7g',
    desc_eng: 'Lip Therapy Rosy Lip',
    price: 59000,
    old_price: 82000,
    discount: '28%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-100540031-1689391938_img_380x380_64adc6_fit_center.jpg',
    rating: 4.79,
    rates: 35,
    products_sold: '965',
  },
  {
    _id: '422206149',
    name: 'Combo 4 Bông Tẩy Trang Ceiba 100% Chất Liệu Cotton 140 Miếng',
    category: 'Trang Điểm / Dụng Cụ Trang Điểm / Bông Tẩy Trang',
    brand: 'Ceiba',
    desc_vn: 'Combo 4 Bông Tẩy Trang Ceiba 100% Chất Liệu Cotton 140 Miếng',
    desc_eng: '',
    price: 111000,
    old_price: 170000,
    discount: '35%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-combo-4-bong-tay-trang-ceiba-100-cotton-140-mieng_img_380x380_64adc6_fit_center.jpg',
    rating: 4.29,
    rates: 67,
    products_sold: '506',
  },
  {
    _id: '100230069',
    name: 'Bông Tẩy Trang Silcot Cơ Bản Hộp 82 Miếng',
    category: 'Trang Điểm / Dụng Cụ Trang Điểm / Bông Tẩy Trang',
    brand: 'SILCOT',
    desc_vn: 'Bông Tẩy Trang Silcot Cơ Bản Hộp 82 Miếng',
    desc_eng: 'Silcot Velvety Touch Cotton',
    price: 32000,
    old_price: 44000,
    discount: '27%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-bong-tay-trang-silcot-co-ban-82-mieng-1684394164_img_380x380_64adc6_fit_center.jpg',
    rating: 4.53,
    rates: 99,
    products_sold: '1.755',
  },
  {
    _id: '207500008',
    name: 'Combo 3 Bông Tẩy Trang Silcot Cao Cấp 66 Miếng/Hộp',
    category: 'Trang Điểm / Dụng Cụ Trang Điểm / Bông Tẩy Trang',
    brand: 'SILCOT',
    desc_vn: 'Combo 3 Bông Tẩy Trang Silcot Cao Cấp 66 Miếng/Hộp',
    desc_eng: 'Soft Touch Premium Cotton',
    price: 104000,
    old_price: 132000,
    discount: '21%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-bo-3-hop-bong-tay-trang-cao-cap-silcot-premium-66-mieng-hop-1684400026_img_380x380_64adc6_fit_center.jpg',
    rating: 4.54,
    rates: 114,
    products_sold: '509',
  },
  {
    _id: '422201822',
    name: 'Bông Tẩy Trang LilyBell Lilian Puff Cotton 222 Miếng',
    category: 'Trang Điểm / Dụng Cụ Trang Điểm / Bông Tẩy Trang',
    brand: 'LilyBell',
    desc_vn: 'Bông Tẩy Trang LilyBell Lilian Puff Cotton 222 Miếng',
    desc_eng: 'Lilian Puff Cotton',
    price: 55000,
    old_price: 80000,
    discount: '31%',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-bong-tay-trang-lilybell-lilian-puff-cotton-222-mieng-1_img_380x380_64adc6_fit_center.jpg',
    rating: 4.21,
    rates: 31,
    products_sold: '960',
  },
  {
    _id: '100830002',
    name: 'Nước Tẩy Trang Mắt Môi Maybelline 150ml',
    category: 'Trang Điểm / Trang Điểm Môi / Tẩy Trang Mắt / Môi',
    brand: 'MAYBELLINE',
    desc_vn: 'Nước Tẩy Trang Mắt Môi Maybelline 150ml',
    desc_eng: 'Lip & Eye Make Up Remover',
    price: 139000,
    old_price: 149000,
    discount: '7%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-nuoc-tay-trang-mat-moi-maybelline-150ml-1688613613_img_380x380_64adc6_fit_center.jpg',
    rating: 4.72,
    rates: 74,
    products_sold: '369',
  },
  {
    _id: '237800005',
    name: 'Bông Tẩy Trang Mihoo Bông Tròn Túi 200 Miếng',
    category: 'Trang Điểm / Dụng Cụ Trang Điểm / Bông Tẩy Trang',
    brand: 'MIHOO',
    desc_vn: 'Bông Tẩy Trang Mihoo Bông Tròn Túi 200 Miếng',
    desc_eng: 'Mermaid Cotton Pads',
    price: 54000,
    old_price: 58000,
    discount: '7%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-bong-tay-trang-mihoo-bong-tron-tui-200-mieng_img_380x380_64adc6_fit_center.jpg',
    rating: 4.75,
    rates: 147,
    products_sold: '929',
  },
  {
    _id: '422209457',
    name: 'Son Kem Lì Black Rouge A12 Dashed Brown Nâu Gạch 4.5g',
    category: 'Trang Điểm / Trang Điểm Môi / Son Kem / Tint',
    brand: 'Black Rouge',
    desc_vn: 'Son Kem Lì Black Rouge A12 Dashed Brown Nâu Gạch 4.5g',
    desc_eng: 'Air Fit Velvet Ver 2 Mood Filter #A12 Dashed Brown',
    price: 164000,
    old_price: 298000,
    discount: '45%',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping_422209457-1686900671_img_380x380_64adc6_fit_center.jpg',
    rating: 4.75,
    rates: 136,
    products_sold: '299',
  },
  {
    _id: '422203712',
    name: 'Phấn Nước Gilaa Kiềm Dầu Và Dưỡng Da #02 Natural Beige 13g',
    category: 'Trang Điểm / Trang Điểm Mặt / Phấn Nước Cushion',
    brand: 'Gilaa',
    desc_vn: 'Phấn Nước Gilaa Kiềm Dầu Và Dưỡng Da #02 Natural Beige 13g',
    desc_eng: 'Long Wear DD Cushion #02 Natural Beige',
    price: 315000,
    old_price: 525000,
    discount: '40%',
    image:
      'https://media.hasaki.vn/catalog/product/p/h/phan-nuoc-gilaa-kiem-dau-va-duong-da-2-natural-beige-13g-10_img_380x380_64adc6_fit_center.jpg',
    rating: 4.14,
    rates: 49,
    products_sold: '134',
  },
  {
    _id: '422203711',
    name: 'Phấn Nước Gilaa Kiềm Dầu Và Dưỡng Da #01 Light Beige 13g',
    category: 'Trang Điểm / Trang Điểm Mặt / Phấn Nước Cushion',
    brand: 'Gilaa',
    desc_vn: 'Phấn Nước Gilaa Kiềm Dầu Và Dưỡng Da #01 Light Beige 13g',
    desc_eng: 'Long Wear DD Cushion #01 Light Beige',
    price: 330000,
    old_price: 525000,
    discount: '37%',
    image:
      'https://media.hasaki.vn/catalog/product/p/h/phan-nuoc-gilaa-kiem-dau-va-duong-da-01-light-beige-13g-1_img_380x380_64adc6_fit_center.jpg',
    rating: 4.9,
    rates: 140,
    products_sold: '124',
  },
  {
    _id: '422203809',
    name: 'Combo 3 Bông Tẩy Trang Ipek 150 Miếng',
    category: 'Trang Điểm / Dụng Cụ Trang Điểm / Bông Tẩy Trang',
    brand: 'Ipek Klasik',
    desc_vn: 'Combo 3 Bông Tẩy Trang Ipek 150 Miếng',
    desc_eng: 'Cotton Pads',
    price: 83000,
    old_price: 150000,
    discount: '45%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-combo-3-bong-tay-trang-ipek-150-mieng_img_380x380_64adc6_fit_center.jpg',
    rating: 4.83,
    rates: 124,
    products_sold: '484',
  },
  {
    _id: '422200147',
    name: 'Kem Nền Maybelline Mịn Nhẹ Kiềm Dầu Chống Nắng #112 30ml',
    category: 'Trang Điểm / Trang Điểm Mặt / Kem Nền',
    brand: 'MAYBELLINE',
    desc_vn: 'Kem Nền Maybelline Mịn Nhẹ Kiềm Dầu Chống Nắng #112 30ml',
    desc_eng: 'Fit Me Matte Poreless Foundation SPF 22 #112 Natural Ivory',
    price: 198000,
    old_price: 268000,
    discount: '26%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-kem-nen-maybelline-min-nhe-kiem-dau-chong-nang-112-30ml_pi8MufZ2mbSAXkav_img_380x380_64adc6_fit_center.png',
    rating: 4.57,
    rates: 85,
    products_sold: '198',
  },
  {
    _id: '100740010',
    name: 'Mascara Maybelline Dài Mi và Cong Mi, Chuốt Mi Đen 9.2ml',
    category: 'Trang Điểm / Trang Điểm Mắt / Mascara',
    brand: 'MAYBELLINE',
    desc_vn: 'Mascara Maybelline Dài Mi và Cong Mi, Chuốt Mi Đen 9.2ml',
    desc_eng: 'Hyper Curl Waterproof',
    price: 116000,
    old_price: 168000,
    discount: '31%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-mascara-maybelline-lam-cong-mi-100-9-2ml_mCtjvwKC3aPiEU4C_img_380x380_64adc6_fit_center.png',
    rating: 4.13,
    rates: 147,
    products_sold: '328',
  },
  {
    _id: '100600060',
    name: 'Kem Lót Maybelline Mịn Da Che Khuyết Điểm 22ml',
    category: 'Trang Điểm / Trang Điểm Mặt / Kem Lót',
    brand: 'MAYBELLINE',
    desc_vn: 'Kem Lót Maybelline Mịn Da Che Khuyết Điểm 22ml',
    desc_eng: 'Baby Skin Pore Eraser',
    price: 159000,
    old_price: 188000,
    discount: '15%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-kem-lot-trang-diem-maybelline-baby-skin-22ml-1688613950_img_380x380_64adc6_fit_center.jpg',
    rating: 4.41,
    rates: 94,
    products_sold: '236',
  },
  {
    _id: '422203302',
    name: 'Bông Tẩy Trang Mihoo Kokimi Bông Tròn Túi 210 miếng',
    category: 'Trang Điểm / Dụng Cụ Trang Điểm / Bông Tẩy Trang',
    brand: 'MIHOO',
    desc_vn: 'Bông Tẩy Trang Mihoo Kokimi Bông Tròn Túi 210 miếng',
    desc_eng: 'Cotton Pads Jumpo Size 2+1',
    price: 57000,
    old_price: 59000,
    discount: '3%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-bong-tay-trang-mihoo-kokimi-bong-tron-tui-210-mieng_img_380x380_64adc6_fit_center.jpg',
    rating: 4.11,
    rates: 61,
    products_sold: '634',
  },
  {
    _id: '422209315',
    name: 'Mascara Maybelline Tơi Dài Mi Không Giới Hạn 6ml',
    category: 'Trang Điểm / Trang Điểm Mắt / Mascara',
    brand: 'MAYBELLINE',
    desc_vn: 'Mascara Maybelline Tơi Dài Mi Không Giới Hạn 6ml',
    desc_eng: 'Lash Sensational Sky High Waterproof Mascara Makeup',
    price: 209000,
    old_price: 268000,
    discount: '22%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-mascara-maybelline-lam-dai-va-day-mi-mau-very-black-6ml_6E5mLRtPvBbYSY5r_img_380x380_64adc6_fit_center.png',
    rating: 4.83,
    rates: 83,
    products_sold: '146',
  },
  {
    _id: '422211112',
    name: 'Son Bóng Maybelline 130 Extra - Đỏ Nâu Đất 4.2ml',
    category: 'Trang Điểm / Trang Điểm Môi / Son Bóng',
    brand: 'MAYBELLINE',
    desc_vn: 'Son Bóng Maybelline 130 Extra - Đỏ Nâu Đất 4.2ml',
    desc_eng: 'Superstay Vinyl Ink #130 Extra',
    price: 229000,
    old_price: 298000,
    discount: '23%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-son-bong-maybelline-130-extra-do-nau-dat-4-2ml_rqf6S61sun7o6XfM_img_380x380_64adc6_fit_center.png',
    rating: 4.27,
    rates: 33,
    products_sold: '119',
  },
  {
    _id: '422206752',
    name: 'Son Dưỡng Môi Mediheal Ban Ngày Màu Cam 10ml',
    category: 'Trang Điểm / Trang Điểm Môi / Son Dưỡng Môi',
    brand: 'MEDIHEAL',
    desc_vn: 'Son Dưỡng Môi Mediheal Ban Ngày Màu Cam 10ml',
    desc_eng: 'Labocare Pantenolips Healssence Coral',
    price: 60000,
    old_price: 143000,
    discount: '58%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-son-duong-mediheal-am-muot-min-mang-lam-hong-moi-10ml-1681273295_img_380x380_64adc6_fit_center.jpg',
    rating: 4.21,
    rates: 130,
    products_sold: '450',
  },
  {
    _id: '234300023',
    name: 'Son Dưỡng Môi Mediheal Ban Đêm Không Màu 10ml',
    category: 'Trang Điểm / Trang Điểm Môi / Son Dưỡng Môi',
    brand: 'MEDIHEAL',
    desc_vn: 'Son Dưỡng Môi Mediheal Ban Đêm Không Màu 10ml',
    desc_eng: 'Labocare Paneno Lips Healbalm',
    price: 58000,
    old_price: 143000,
    discount: '59%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-son-duong-mediheal-lam-mem-vet-tham-mem-moi-10ml-1681272838_img_380x380_64adc6_fit_center.jpg',
    rating: 4.64,
    rates: 134,
    products_sold: '465',
  },
  {
    _id: '205600391',
    name: 'Kem Nền Maybelline Mịn Nhẹ Kiềm Dầu Chống Nắng #120 30ml',
    category: 'Trang Điểm / Trang Điểm Mặt / Kem Nền',
    brand: 'MAYBELLINE',
    desc_vn: 'Kem Nền Maybelline Mịn Nhẹ Kiềm Dầu Chống Nắng #120 30ml',
    desc_eng: 'Fit Me Matte Poreless Foundation SPF 22 - 120 Classic Ivory',
    price: 198000,
    old_price: 268000,
    discount: '26%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-kem-nen-maybelline-min-nhe-kiem-dau-chong-nang-120-classic-ivory-30ml_hZR5HRn7k9qMjQqs_img_380x380_64adc6_fit_center.png',
    rating: 4.86,
    rates: 64,
    products_sold: '123',
  },
  {
    _id: '100760007',
    name: 'Phim Thấm Dầu Jomi 70 Tờ',
    category: 'Trang Điểm / Dụng Cụ Trang Điểm / Giấy Thấm Dầu',
    brand: 'JOMI',
    desc_vn: 'Phim Thấm Dầu Jomi 70 Tờ',
    desc_eng: 'Oil Clear Film',
    price: 48000,
    old_price: 60000,
    discount: '20%',
    image:
      'https://media.hasaki.vn/catalog/product/p/h/phim-tham-dau-jomi-70-to--goi_img_380x380_64adc6_fit_center.jpg',
    rating: 4.02,
    rates: 42,
    products_sold: '506',
  },
  {
    _id: '422205181',
    name: 'Combo 2 Bông Tẩy Trang Ceiba 100% Chất Liệu Cotton 140 Miếng',
    category: 'Trang Điểm / Dụng Cụ Trang Điểm / Bông Tẩy Trang',
    brand: 'Ceiba',
    desc_vn: 'Combo 2 Bông Tẩy Trang Ceiba 100% Chất Liệu Cotton 140 Miếng',
    desc_eng: '100% Cotton Tree',
    price: 56000,
    old_price: 90000,
    discount: '38%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-combo-2-bong-tay-trang-ceiba-100-chat-lieu-cotton-140-mieng_img_380x380_64adc6_fit_center.jpg',
    rating: 4.55,
    rates: 40,
    products_sold: '414',
  },
  {
    _id: '422206303',
    name: 'Son Kem Lì 3CE Sepia - Đỏ Gạch Đậm 4.6g',
    category: 'Trang Điểm / Trang Điểm Môi / Son Kem / Tint',
    brand: '3CE',
    desc_vn: 'Son Kem Lì 3CE Sepia - Đỏ Gạch Đậm 4.6g',
    desc_eng: 'Blur Water Tint',
    price: 272000,
    old_price: 340000,
    discount: '20%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-son-kem-3ce-blur-water-tint-sepia-mau-do-gach-4-6g_7Hd7Uc2xR2WZeFhz_img_380x380_64adc6_fit_center.png',
    rating: 4.37,
    rates: 80,
    products_sold: '85',
  },
  {
    _id: '367800039',
    name: 'Xịt Khoá Makeup Australis Dạng Lì Kiềm Dầu 150ml',
    category: 'Trang Điểm / Trang Điểm Mặt / Xịt Khoá Makeup',
    brand: 'australis',
    desc_vn: 'Xịt Khoá Makeup Australis Dạng Lì Kiềm Dầu 150ml',
    desc_eng: 'Make Up Finishing Spritz Matte',
    price: 256000,
    old_price: 320000,
    discount: '20%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-xit-khoa-lop-trang-diem-australis-dang-li-kiem-dau-150ml-1676615031_img_380x380_64adc6_fit_center.jpg',
    rating: 4.35,
    rates: 142,
    products_sold: '84',
  },
  {
    _id: '100100001',
    name: 'Sáp Dưỡng Ẩm Vaseline Original Healing Jelly 49g',
    category: 'Chăm Sóc Cơ Thể / Dưỡng Thể',
    brand: 'VASELINE',
    desc_vn: 'Sáp Dưỡng Ẩm Vaseline Original Healing Jelly 49g',
    desc_eng: 'Original Healing Jelly',
    price: 41000,
    old_price: 65000,
    discount: '37%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-sap-vaseline-pure-petroleum-jelly-49gr_KtddzzYeTCejEkEJ_img_380x380_64adc6_fit_center.png',
    rating: 4.01,
    rates: 71,
    products_sold: '522',
  },
  {
    _id: '422206784',
    name: 'Bút Kẻ Mắt Lemonade Supertiger Micro #01 Black Màu Đen 1g',
    category: 'Trang Điểm / Trang Điểm Mắt / Kẻ Mắt',
    brand: 'LEMONADE',
    desc_vn: 'Bút Kẻ Mắt Lemonade Supertiger Micro #01 Black Màu Đen 1g',
    desc_eng: 'SuperTiger Micro Eyeliner #01 Black',
    price: 164000,
    old_price: 219000,
    discount: '25%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-422206784-1687927426_img_380x380_64adc6_fit_center.jpg',
    rating: 4.69,
    rates: 142,
    products_sold: '125',
  },
  {
    _id: '422211114',
    name: 'Son Bóng Maybelline 61 Risky - Gạch Đun 4.2ml',
    category: 'Trang Điểm / Trang Điểm Môi / Son Bóng',
    brand: 'MAYBELLINE',
    desc_vn: 'Son Bóng Maybelline 61 Risky - Gạch Đun 4.2ml',
    desc_eng: 'Superstay Vinyl Ink #61 Risky',
    price: 229000,
    old_price: 298000,
    discount: '23%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-son-bong-maybelline-61-risky-gach-dun-4-2ml_9yg7TCowgHXYFZBB_img_380x380_64adc6_fit_center.png',
    rating: 4.61,
    rates: 66,
    products_sold: '88',
  },
  {
    _id: '422205444',
    name: 'Phấn Nước Lemonade Siêu Kiềm Dầu Màu 01 Light 15g',
    category: 'Trang Điểm / Trang Điểm Mặt / Phấn Nước Cushion',
    brand: 'LEMONADE',
    desc_vn: 'Phấn Nước Lemonade Siêu Kiềm Dầu Màu 01 Light 15g',
    desc_eng: 'Supermatte Cushion',
    price: 244000,
    old_price: 349000,
    discount: '30%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-422205444-1687940366_img_380x380_64adc6_fit_center.jpg',
    rating: 4.76,
    rates: 63,
    products_sold: '81',
  },
  {
    _id: '100610048',
    name: 'Kem Che Khuyết Điểm Maybelline Mịn Lì 10 Light 6.8ml',
    category: 'Trang Điểm / Trang Điểm Mặt / Che Khuyết Điểm',
    brand: 'MAYBELLINE',
    desc_vn: 'Kem Che Khuyết Điểm Maybelline Mịn Lì 10 Light 6.8ml',
    desc_eng: 'Fit Me Concealer',
    price: 121000,
    old_price: 158000,
    discount: '23%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-che-khuyet-diem-maybelline-min-li-10-light-leger-6-8ml_aWZR6ZnAMEKcwJAj_img_380x380_64adc6_fit_center.png',
    rating: 4.46,
    rates: 39,
    products_sold: '160',
  },

  {
    _id: '422210625',
    name: 'Nước Hoa Vùng Kín Foellie Hương Hoa Hồng Mạnh Mẽ 5ml ',
    category: 'Nước Hoa / Nước Hoa Vùng Kín',
    brand: 'Foellie',
    desc_vn: 'Nước Hoa Vùng Kín Foellie Hương Hoa Hồng Mạnh Mẽ 5ml',
    desc_eng: 'Inner Perfume #Eau De Bijou',
    price: 154000,
    old_price: 350000,
    discount: '56%',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-nuoc-hoa-vung-kin-foellie-huong-hoa-hong-manh-me-5ml-1670490732_img_380x380_64adc6_fit_center.jpg',
    rating: 4.99,
    rates: 38,
    products_sold: '207',
  },
  {
    _id: '328700016',
    name: 'Nước Hoa Nữ Diamond Femme 45ml (Trắng)',
    category: 'Nước Hoa / Nước Hoa Nữ',
    brand: 'DIAMOND',
    desc_vn: 'Nước Hoa Nữ Diamond Femme 45ml (Trắng)',
    desc_eng: 'Eau De Parfum',
    price: 356000,
    old_price: 549000,
    discount: '35%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-nuoc-hoa-nu-laura-anne-diamond-femme-45ml_thxqViV39s9TQWoQ_img_380x380_64adc6_fit_center.png',
    rating: 4.53,
    rates: 82,
    products_sold: '61',
  },
  {
    _id: '422204134',
    name: 'Nước Hoa Nữ De Memoria #02 Val De Loire Hương Tươi Mát 30ml',
    category: 'Nước Hoa / Nước Hoa Nữ',
    brand: 'De Memoria',
    desc_vn: 'Nước Hoa Nữ De Memoria #02 Val De Loire Hương Tươi Mát 30ml',
    desc_eng: 'Eau De Parfum',
    price: 330000,
    old_price: 550000,
    discount: '40%',
    image:
      'https://media.hasaki.vn/catalog/product/n/u/nuoc-hoa-de-memoria-02-val-de-loire-huong-tuoi-mat-30ml-2_img_380x380_64adc6_fit_center.jpg',
    rating: 4.52,
    rates: 51,
    products_sold: '52',
  },
  {
    _id: '422206568',
    name: 'Nước Hoa Nữ Moschino Toy 2 EDP 100ml',
    category: 'Nước Hoa / Nước Hoa Nữ',
    brand: 'Moschino',
    desc_vn: 'Nước Hoa Nữ Moschino Toy 2 EDP 100ml',
    desc_eng: 'Toy 2 Eau De Parfum',
    price: 1429000,
    old_price: 2442000,
    discount: '41%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-nuoc-hoa-nu-moschino-toy-2-eau-de-parfum-100ml-1655094601_img_380x380_64adc6_fit_center.jpg',
    rating: 4.6,
    rates: 99,
    products_sold: '10',
  },
  {
    _id: '422206562',
    name: 'Nước Hoa Nam Versace Eros EDP 100ml',
    category: 'Nước Hoa / Nước Hoa Nam',
    brand: 'Versace',
    desc_vn: 'Nước Hoa Nam Versace Eros EDP 100ml',
    desc_eng: 'Eros Eau De Parfum Natural Spray',
    price: 1795000,
    old_price: 2761000,
    discount: '35%',
    image:
      'https://media.hasaki.vn/catalog/product/n/u/nuoc-hoa-nam-versace-eros-eau-de-parfum-100ml-1-1654917811_img_380x380_64adc6_fit_center.jpg',
    rating: 4.3,
    rates: 97,
    products_sold: '6',
  },
  {
    _id: '328700014',
    name: 'Nước Hoa Nữ Gennie Little Gold Dress 50ml',
    category: 'Nước Hoa / Nước Hoa Nữ',
    brand: 'Gennie',
    desc_vn: 'Nước Hoa Nữ Gennie Little Gold Dress 50ml',
    desc_eng: 'Little Gold Dress',
    price: 164000,
    old_price: 219000,
    discount: '25%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-nuoc-hoa-nu-gennie-little-gold-dress-50ml_Pyx69My7AmNdJjMr_img_380x380_64adc6_fit_center.png',
    rating: 4.94,
    rates: 61,
    products_sold: '62',
  },
  {
    _id: '422205057',
    name: 'Xịt Thơm Toàn Thân Malissa Kiss Hương Crazy in Love 88ml',
    category: 'Nước Hoa / Xịt Thơm Toàn Thân',
    brand: 'Malissa Kiss',
    desc_vn: 'Xịt Thơm Toàn Thân Malissa Kiss Hương Crazy in Love 88ml',
    desc_eng: 'Perfume Body Mist #Crazy in Love',
    price: 126000,
    old_price: 169000,
    discount: '25%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-xit-thom-toan-than-malissa-kiss-huong-crazy-in-love-88ml_img_380x380_64adc6_fit_center.jpg',
    rating: 4.15,
    rates: 53,
    products_sold: '77',
  },
  {
    _id: '422201176',
    name: 'Nước Hoa Nữ Diamond Femme Pink 45ml (Hồng)',
    category: 'Nước Hoa / Nước Hoa Nữ',
    brand: 'DIAMOND',
    desc_vn: 'Nước Hoa Nữ Diamond Femme Pink 45ml (Hồng)',
    desc_eng: 'Eau De Parfum',
    price: 299000,
    old_price: 549000,
    discount: '46%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-nuoc-hoa-nu-laura-anne-diamond-pour-femme-edp-45ml-hong_Yx1kn9tKsp9EQx5c_img_380x380_64adc6_fit_center.png',
    rating: 4.22,
    rates: 119,
    products_sold: '30',
  },
  {
    _id: '328700017',
    name: 'Nước Hoa Nam Diamond Homme 45ml (Đen)',
    category: 'Nước Hoa / Nước Hoa Nam',
    brand: 'DIAMOND',
    desc_vn: 'Nước Hoa Nam Diamond Homme 45ml (Đen)',
    desc_eng: 'Eau De Parfum',
    price: 357000,
    old_price: 549000,
    discount: '35%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-nuoc-hoa-nam-laura-anne-diamond-homme-45ml_Gib9jmeP5H6mShC7_img_380x380_64adc6_fit_center.png',
    rating: 4.79,
    rates: 95,
    products_sold: '25',
  },
  {
    _id: '422210935',
    name: 'Nước Hoa Vùng Kín Foellie Hương Trái Cây Ngọt Ngào 5ml',
    category: 'Nước Hoa / Nước Hoa Vùng Kín',
    brand: 'Foellie',
    desc_vn: 'Nước Hoa Vùng Kín Foellie Hương Trái Cây Ngọt Ngào 5ml',
    desc_eng: 'Inner Perfume #Eau De Fleur',
    price: 179000,
    old_price: 350000,
    discount: '49%',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-nuoc-hoa-vung-kin-foellie-huong-trai-cay-ngot-ngao-5ml-1672385029_img_380x380_64adc6_fit_center.jpg',
    rating: 4.69,
    rates: 71,
    products_sold: '36',
  },
  {
    _id: '422205247',
    name: 'Nước Hoa Nữ Gennie Little Rose Dress Bản Giới Hạn 50ml',
    category: 'Nước Hoa / Nước Hoa Nữ',
    brand: 'Gennie',
    desc_vn: 'Nước Hoa Nữ Gennie Little Rose Dress Bản Giới Hạn 50ml',
    desc_eng: 'Little Rose Dress For Her',
    price: 238000,
    old_price: 349000,
    discount: '32%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-nuoc-hoa-nu-gennie-little-rose-dress-ban-gioi-han-50ml_Ubf4um6UcHdCZjHQ_img_380x380_64adc6_fit_center.png',
    rating: 4.21,
    rates: 128,
    products_sold: '27',
  },
  {
    _id: '422207523',
    name: 'Nước Hoa Nam Nữ Calvin Klein Everyone EDT 100ml',
    category: 'Nước Hoa / Nước Hoa Nam',
    brand: 'Calvin Klein',
    desc_vn: 'Nước Hoa Nam Nữ Calvin Klein Everyone EDT 100ml',
    desc_eng: 'Everyone Eau de Toilette',
    price: 1342000,
    old_price: 2130000,
    discount: '37%',
    image:
      'https://media.hasaki.vn/catalog/product/n/u/nuoc-hoa-nam-nu-calvin-klein-everyone-edt-100ml-1-1654676138_img_380x380_64adc6_fit_center.jpg',
    rating: 4.18,
    rates: 32,
    products_sold: '5',
  },
  {
    _id: '422206554',
    name: 'Nước Hoa Nữ Versace Bright Crystal Absolu EDP 90ml',
    category: 'Nước Hoa / Nước Hoa Nữ',
    brand: 'Versace',
    desc_vn: 'Nước Hoa Nữ Versace Bright Crystal Absolu EDP 90ml',
    desc_eng: 'Bright Crystal Absolu Eau de Parfum Natural Spray',
    price: 1895000,
    old_price: 2915000,
    discount: '35%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-nuoc-hoa-nu-versace-bright-crystal-absolu-edp-90ml-1644828618_img_380x380_64adc6_fit_center.jpg',
    rating: 4.91,
    rates: 56,
    products_sold: '3',
  },
  {
    _id: '422201932',
    name: 'Nước Hoa Nữ Pinker Bell 04 Lovey Day EDP 30ml',
    category: 'Nước Hoa / Nước Hoa Nữ',
    brand: 'Pinker Bell',
    desc_vn: 'Nước Hoa Nữ Pinker Bell 04 Lovey Day EDP 30ml',
    desc_eng: 'Eau De Perfume #Lovey Day',
    price: 274000,
    old_price: 450000,
    discount: '39%',
    image:
      'https://media.hasaki.vn/catalog/product/n/u/nuoc-hoa-pinker-bell-04-lovey-day-edp-30ml-1_img_380x380_64adc6_fit_center.jpg',
    rating: 4.37,
    rates: 90,
    products_sold: '21',
  },
  {
    _id: '422204137',
    name: 'Nước Hoa Nữ De Memoria #05 Montpellier Hương Ngọt Ngào 30ml',
    category: 'Nước Hoa / Nước Hoa Nữ',
    brand: 'De Memoria',
    desc_vn: 'Nước Hoa Nữ De Memoria #05 Montpellier Hương Ngọt Ngào 30ml',
    desc_eng: 'Eau De Parfum',
    price: 354000,
    old_price: 550000,
    discount: '36%',
    image:
      'https://media.hasaki.vn/catalog/product/n/u/nuoc-hoa-nu-de-memoria-05-montpellier-huong-quyen-ru-30ml-1_img_380x380_64adc6_fit_center.jpg',
    rating: 4.32,
    rates: 119,
    products_sold: '16',
  },
  {
    _id: '422204133',
    name: 'Nước Hoa Nữ De Memoria #01 Spello Hương Mê Hoặc 30ml',
    category: 'Nước Hoa / Nước Hoa Nữ',
    brand: 'De Memoria',
    desc_vn: 'Nước Hoa Nữ De Memoria #01 Spello Hương Mê Hoặc 30ml',
    desc_eng: 'Eau De Parfum',
    price: 330000,
    old_price: 550000,
    discount: '40%',
    image:
      'https://media.hasaki.vn/catalog/product/n/u/nuoc-hoa-de-memoria-01-spello-huong-me-hoac-30ml-1_img_380x380_64adc6_fit_center.jpg',
    rating: 4.52,
    rates: 77,
    products_sold: '17',
  },
  {
    _id: '352900002',
    name: 'Nước Hoa Nam Gota Iconic Eau de Parfum 50ml',
    category: 'Nước Hoa / Nước Hoa Nam',
    brand: 'Gota',
    desc_vn: 'Nước Hoa Nam Gota Iconic Eau de Parfum 50ml',
    desc_eng: 'Iconic Perfume For Men Eau de Parfum',
    price: 197000,
    old_price: 296000,
    discount: '33%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-nuoc-hoa-nam-gota-iconic-50ml_3vGNR328CeCWey1X_img_380x380_64adc6_fit_center.png',
    rating: 4.57,
    rates: 118,
    products_sold: '26',
  },
  {
    _id: '422204135',
    name: 'Nước Hoa Nữ De Memoria #03 Granada Hương Quyến Rũ 30ml',
    category: 'Nước Hoa / Nước Hoa Nữ',
    brand: 'De Memoria',
    desc_vn: 'Nước Hoa Nữ De Memoria #03 Granada Hương Quyến Rũ 30ml',
    desc_eng: 'Eau De Parfum',
    price: 330000,
    old_price: 550000,
    discount: '40%',
    image:
      'https://media.hasaki.vn/catalog/product/n/u/nuoc-hoa-nu-de-memoria-03-granada-huong-quyen-ru-30ml-1_img_380x380_64adc6_fit_center.jpg',
    rating: 4.58,
    rates: 75,
    products_sold: '14',
  },
  {
    _id: '352900001',
    name: 'Nước Hoa Nam Gota Bouncy Eau de Parfum 50ml',
    category: 'Nước Hoa / Nước Hoa Nam',
    brand: 'Gota',
    desc_vn: 'Nước Hoa Nam Gota Bouncy Eau de Parfum 50ml',
    desc_eng: 'Bouncy Perfume For Men Eau de Parfum',
    price: 191000,
    old_price: 296000,
    discount: '35%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-nuoc-hoa-nam-gota-bouncy-50ml_hZzzceCqdbZTSwve_img_380x380_64adc6_fit_center.png',
    rating: 4.8,
    rates: 88,
    products_sold: '24',
  },
  {
    _id: '328700003',
    name: 'Nước Hoa Nữ Laura Anne Allure For Her 50ml (Hồng)',
    category: 'Nước Hoa / Nước Hoa Nữ',
    brand: 'LAURA ANNE',
    desc_vn: 'Nước Hoa Nữ Laura Anne Allure For Her 50ml (Hồng)',
    desc_eng: 'Eau de Parfum',
    price: 178000,
    old_price: 299000,
    discount: '40%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-nuoc-hoa-nu-laura-anne-allure-50ml_c5bWFhJczcBgktM5_img_380x380_64adc6_fit_center.png',
    rating: 4.83,
    rates: 44,
    products_sold: '25',
  },
  {
    _id: '422210939',
    name: 'Nước Hoa Vùng Kín Foellie Hương Hoa Hồng Trắng 5ml',
    category: 'Nước Hoa / Nước Hoa Vùng Kín',
    brand: 'Foellie',
    desc_vn: 'Nước Hoa Vùng Kín Foellie Hương Hoa Hồng Trắng 5ml',
    desc_eng: 'Inner Perfume #Eau De Ciel',
    price: 160000,
    old_price: 350000,
    discount: '54%',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-nuoc-hoa-vung-kin-foellie-huong-hoa-hong-trang-5ml-1672375974_img_380x380_64adc6_fit_center.jpg',
    rating: 4.09,
    rates: 108,
    products_sold: '27',
  },
  {
    _id: '422204136',
    name: 'Nước Hoa Nữ De Memoria #04 Dresden Hương Sành Điệu 30ml',
    category: 'Nước Hoa / Nước Hoa Nữ',
    brand: 'De Memoria',
    desc_vn: 'Nước Hoa Nữ De Memoria #04 Dresden Hương Sành Điệu 30ml',
    desc_eng: 'Eau De Parfum',
    price: 330000,
    old_price: 550000,
    discount: '40%',
    image:
      'https://media.hasaki.vn/catalog/product/n/u/nuoc-hoa-nu-de-memoria-04-dresden-chic-huong-sanh-dieu-30ml-1_img_380x380_64adc6_fit_center.jpg',
    rating: 4.74,
    rates: 114,
    products_sold: '12',
  },
  {
    _id: '422210942',
    name: 'Nước Hoa Vùng Kín Foellie Cherry Đen Bản Giới Hạn 5ml',
    category: 'Nước Hoa / Nước Hoa Vùng Kín',
    brand: 'Foellie',
    desc_vn: 'Nước Hoa Vùng Kín Foellie Cherry Đen Bản Giới Hạn 5ml',
    desc_eng: 'Inner Perfume #Eau De Noir',
    price: 160000,
    old_price: 350000,
    discount: '54%',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-nuoc-hoa-vung-kin-foellie-huong-cherry-den-ngot-ngao-5ml-1672373307_img_380x380_64adc6_fit_center.jpg',
    rating: 4.95,
    rates: 140,
    products_sold: '24',
  },
  {
    _id: '328700013',
    name: 'Nước Hoa Nữ Gennie Little Black Dress 50ml',
    category: 'Nước Hoa / Nước Hoa Nữ',
    brand: 'Gennie',
    desc_vn: 'Nước Hoa Nữ Gennie Little Black Dress 50ml',
    desc_eng: 'Little Black Dress',
    price: 164000,
    old_price: 219000,
    discount: '25%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-nuoc-hoa-nu-gennie-little-black-dress-50ml_1L3BtiA7yuoKk65G_img_380x380_64adc6_fit_center.png',
    rating: 4.9,
    rates: 149,
    products_sold: '23',
  },
  {
    _id: '352900004',
    name: 'Nước Hoa Nam Gota Urban Eau de Parfum 50ml',
    category: 'Nước Hoa / Nước Hoa Nam',
    brand: 'Gota',
    desc_vn: 'Nước Hoa Nam Gota Urban Eau de Parfum 50ml',
    desc_eng: 'Urban Perfume For Men Eau de Parfum',
    price: 197000,
    old_price: 296000,
    discount: '33%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-nuoc-hoa-nam-gota-urban-50ml_PVV1tP1uGCaaPdvm_img_380x380_64adc6_fit_center.png',
    rating: 4.49,
    rates: 96,
    products_sold: '18',
  },
  {
    _id: '422204138',
    name: 'Nước Hoa Nữ De Memoria #06 Grasse Hương Đáng Yêu 30ml',
    category: 'Nước Hoa / Nước Hoa Nữ',
    brand: 'De Memoria',
    desc_vn: 'Nước Hoa Nữ De Memoria #06 Grasse Hương Đáng Yêu 30ml',
    desc_eng: 'Eau De Parfum',
    price: 354000,
    old_price: 550000,
    discount: '36%',
    image:
      'https://media.hasaki.vn/catalog/product/n/u/nuoc-hoa-nu-de-memoria-06-grasse-huong-dang-yeu-30ml-1_img_380x380_64adc6_fit_center.jpg',
    rating: 4.1,
    rates: 52,
    products_sold: '9',
  },
  {
    _id: '422210931',
    name: 'Nước Hoa Nam Diamond Homme Dark Blue 45ml (Xanh)',
    category: 'Nước Hoa / Nước Hoa Nam',
    brand: 'DIAMOND',
    desc_vn: 'Nước Hoa Nam Diamond Homme Dark Blue 45ml (Xanh)',
    desc_eng: 'Eau De Parfum',
    price: 383000,
    old_price: 549000,
    discount: '30%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-nuoc-hoa-nam-laura-anne-diamond-homme-dark-blue-edp-45ml_mVqPA9VdFdpnJKya_img_380x380_64adc6_fit_center.png',
    rating: 4.01,
    rates: 67,
    products_sold: '9',
  },
  {
    _id: '422207782',
    name: 'Nước Hoa Nam Diamond Homme Brown 45ml (Nâu)',
    category: 'Nước Hoa / Nước Hoa Nam',
    brand: 'DIAMOND',
    desc_vn: 'Nước Hoa Nam Diamond Homme Brown 45ml (Nâu)',
    desc_eng: 'Eau De Parfum',
    price: 329000,
    old_price: 499000,
    discount: '34%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-nuoc-hoa-nam-laura-anne-diamond-pour-homme-45ml-nau_mEcKMEwfXLM1fDtD_img_380x380_64adc6_fit_center.png',
    rating: 4.94,
    rates: 82,
    products_sold: '10',
  },
  {
    _id: '422207529',
    name: 'Nước Hoa Nữ Burberry Her EDP 100ml',
    category: 'Nước Hoa / Nước Hoa Nữ',
    brand: 'BURBERRY',
    desc_vn: 'Nước Hoa Nữ Burberry Her EDP 100ml',
    desc_eng: 'Her Eau De Parfum',
    price: 2967000,
    old_price: 4990000,
    discount: '41%',
    image:
      'https://media.hasaki.vn/catalog/product/n/u/nuoc-hoa-nu-burberry-her-eau-de-parfum-100ml-1-1654670613_img_380x380_64adc6_fit_center.jpg',
    rating: 4.6,
    rates: 82,
    products_sold: '1',
  },
  {
    _id: '422207525',
    name: 'Nước Hoa Nam Calvin Klein Defy EDT 100ml',
    category: 'Nước Hoa / Nước Hoa Nam',
    brand: 'Calvin Klein',
    desc_vn: 'Nước Hoa Nam Calvin Klein Defy EDT 100ml',
    desc_eng: 'Defy Eau de Toilette Spray',
    price: 1457000,
    old_price: 2760000,
    discount: '47%',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-nuoc-hoa-nam-calvin-klein-defy-edt-100ml-1654654610_img_380x380_64adc6_fit_center.jpg',
    rating: 4.95,
    rates: 82,
    products_sold: '2',
  },
  {
    _id: '255300015',
    name: 'Nước Hoa Nam Versace Pour Homme EDT 50ml',
    category: 'Nước Hoa / Nước Hoa Nam',
    brand: 'Versace',
    desc_vn: 'Nước Hoa Nam Versace Pour Homme EDT 50ml',
    desc_eng: 'Pour Homme Eau De Toilette Spray',
    price: 1443000,
    old_price: 1782000,
    discount: '19%',
    image:
      'https://media.hasaki.vn/catalog/product/n/u/nuoc-hoa-nam-versace-pour-homme-edt-50ml-1-1672212201_img_380x380_64adc6_fit_center.jpg',
    rating: 4.71,
    rates: 34,
    products_sold: '2',
  },
  {
    _id: '422209059',
    name: '[Mini] Nước Hoa Nữ Lancôme La Vie Est Belle EDP 10ml',
    category: 'Mini / Sample',
    brand: 'LANCÔME',
    desc_vn: '[Mini] Nước Hoa Nữ Lancôme La Vie Est Belle EDP 10ml',
    desc_eng: 'La Vie Est Belle Eau de Parfum',
    price: 550000,
    old_price: null,
    discount: null,
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-nuoc-hoa-nu-lancome-la-vie-est-belle-10ml-1662605582_img_380x380_64adc6_fit_center.jpg',
    rating: 4.32,
    rates: 59,
    products_sold: '5',
  },
  {
    _id: '422210930',
    name: 'Nước Hoa Nữ Diamond Femme Ruby Red 45ml (Đỏ)',
    category: 'Nước Hoa / Nước Hoa Nữ',
    brand: 'DIAMOND',
    desc_vn: 'Nước Hoa Nữ Diamond Femme Ruby Red 45ml (Đỏ)',
    desc_eng: 'Eau De Parfum',
    price: 299000,
    old_price: 549000,
    discount: '46%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-nuoc-hoa-nu-laura-anne-diamond-femme-ruby-red-edp-45ml_4rLnsXUQ5LsMiUMg_img_380x380_64adc6_fit_center.png',
    rating: 4.53,
    rates: 113,
    products_sold: '10',
  },
  {
    _id: '422207515',
    name: 'Nước Hoa Nữ Burberry Her Blossom EDT 100ml',
    category: 'Nước Hoa / Nước Hoa Nữ',
    brand: 'BURBERRY',
    desc_vn: 'Nước Hoa Nữ Burberry Her Blossom EDT 100ml',
    desc_eng: 'Her Blossom Eau de Toilette',
    price: 2703000,
    old_price: 4030000,
    discount: '33%',
    image:
      'https://media.hasaki.vn/catalog/product/n/u/nuoc-hoa-nu-burberry-her-blossom-edt-100ml-1-1654595842_img_380x380_64adc6_fit_center.jpg',
    rating: 4.83,
    rates: 59,
    products_sold: '1',
  },
  {
    _id: '328700004',
    name: 'Nước Hoa Nam Laura Anne Allure For Him 50ml (Đỏ)',
    category: 'Nước Hoa / Nước Hoa Nam',
    brand: 'LAURA ANNE',
    desc_vn: 'Nước Hoa Nam Laura Anne Allure For Him 50ml (Đỏ)',
    desc_eng: 'Eau de Parfum',
    price: 148000,
    old_price: 299000,
    discount: '51%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-nuoc-hoa-nam-laura-anne-red-50ml_z9NJ7yGidJ7NdrU8_img_380x380_64adc6_fit_center.png',
    rating: 4.88,
    rates: 77,
    products_sold: '19',
  },
  {
    _id: '422206688',
    name: 'Combo Son Kem Lì Gilaa 08 Take A Sip + Nước Hoa Nữ De Memoria 04 Dresden',
    category: 'Trang Điểm / Trang Điểm Môi / Son Kem / Tint',
    brand: 'Gilaa',
    desc_vn:
      'Combo Son Kem Lì Gilaa 08 Take A Sip + Nước Hoa Nữ De Memoria 04 Dresden',
    desc_eng: '',
    price: 529000,
    old_price: 848000,
    discount: '38%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-hop-qua-son-kem-li-gilaa-08-take-a-sip-nuoc-hoa-nu-de-memoria-04-dresden-1644399929_img_380x380_64adc6_fit_center.jpg',
    rating: 4.53,
    rates: 45,
    products_sold: '5',
  },
  {
    _id: '255500002',
    name: 'Nước Hoa Nữ Salvatore Ferragamo Signorina Misteriosa EDP 50ml',
    category: 'Nước Hoa / Nước Hoa Nữ',
    brand: 'Salvatore Ferragamo',
    desc_vn: 'Nước Hoa Nữ Salvatore Ferragamo Signorina Misteriosa EDP 50ml',
    desc_eng: 'Signorina Misteriosa Eau De Parfum',
    price: 1320000,
    old_price: 2354000,
    discount: '44%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-nuoc-hoa-nu-salvatore-ferragamo-signorina-misteriosa-edp-50ml-1655884821_img_380x380_64adc6_fit_center.jpg',
    rating: 4.63,
    rates: 67,
    products_sold: '2',
  },
  {
    _id: '422201935',
    name: 'Nước Hoa Nữ Pinker Bell 07 Some Day EDP 30ml',
    category: 'Nước Hoa / Nước Hoa Nữ',
    brand: 'Pinker Bell',
    desc_vn: 'Nước Hoa Nữ Pinker Bell 07 Some Day EDP 30ml',
    desc_eng: 'Eau De Perfume #Some Day',
    price: 269000,
    old_price: 450000,
    discount: '40%',
    image:
      'https://media.hasaki.vn/catalog/product/n/u/nuoc-hoa-pinker-bell-07-some-day-edp-30ml-1_img_380x380_64adc6_fit_center.jpg',
    rating: 4.43,
    rates: 138,
    products_sold: '10',
  },
  {
    _id: '422205505',
    name: 'Xịt Thơm Toàn Thân Malissa Kiss Hương Sweet Poison 88ml ',
    category: 'Nước Hoa / Xịt Thơm Toàn Thân',
    brand: 'Malissa Kiss',
    desc_vn: 'Xịt Thơm Toàn Thân Malissa Kiss Hương Sweet Poison 88ml',
    desc_eng: 'Perfume Mist #Sweet Poison',
    price: 126000,
    old_price: 169000,
    discount: '25%',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-xit-thom-toan-than-malissa-kiss-huong-sweet-poison-88ml_img_380x380_64adc6_fit_center.jpg',
    rating: 4.28,
    rates: 86,
    products_sold: '20',
  },
  {
    _id: '422210937',
    name: 'Nước Hoa Vùng Kín Foellie Hương Hoa Anh Đào 5ml',
    category: 'Nước Hoa / Nước Hoa Vùng Kín',
    brand: 'Foellie',
    desc_vn: 'Nước Hoa Vùng Kín Foellie Hương Hoa Anh Đào 5ml',
    desc_eng: 'Inner Perfume #Eau De Cherry Blossom',
    price: 179000,
    old_price: 350000,
    discount: '49%',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-nuoc-hoa-vung-kin-foellie-huong-hoa-anh-dao-5ml-1672382587_img_380x380_64adc6_fit_center.jpg',
    rating: 4.65,
    rates: 69,
    products_sold: '14',
  },

  {
    _id: '422203509',
    name: 'Sữa Tắm Hatomugi Dưỡng Ẩm Sâu & Làm Sáng Da 600ml',
    category: 'Chăm Sóc Cơ Thể / Sữa Tắm',
    brand: 'HATOMUGI',
    desc_vn: 'Sữa Tắm Hatomugi Dưỡng Ẩm Sâu & Làm Sáng Da 600ml',
    desc_eng: 'Reihaku Hatomugi High Moisturizing Body Soap',
    price: 108000,
    old_price: 199000,
    discount: '46%',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-sua-tam-hatomugi-y-di-duong-am-sau-lam-sang-da-600ml-1683254677_img_380x380_64adc6_fit_center.jpg',
    rating: 4.55,
    rates: 149,
    products_sold: '152',
  },
  {
    _id: '100080050',
    name: 'Xịt Khử Mùi Nivea Cho Nữ Sáng Da, Mờ Vết Thâm 150ml',
    category: 'Chăm Sóc Cơ Thể / Khử Mùi / Xịt Khử Mùi',
    brand: "Tesori d'Oriente",
    desc_vn: "Sữa Tắm Nước Hoa Tesori d'Oriente Hương Hoa Sen 250ml",
    desc_eng: 'Shower Cream #Lotus Flower And Shea Butter',
    price: 143000,
    old_price: 175000,
    discount: '18%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-sua-tam-nuoc-hoa-tesori-d-oriente-huong-hoa-sen-250ml_TRhhf9acbf3h9XMU_img_380x380_64adc6_fit_center.png',
    rating: 4.07,
    rates: 111,
    products_sold: '115',
  },
  {
    _id: '422209938',
    name: 'Combo Serum Dưỡng Thể Vaseline Chống Nắng Sáng Da 300mlx2',
    category: 'Chăm Sóc Cơ Thể / Dưỡng Thể',
    brand: 'NIVEA',
    desc_vn: 'Xịt Khử Mùi Nivea Cho Nữ Sáng Da, Mờ Vết Thâm 150ml',
    desc_eng: 'Extra Brightening 8 Super Food Spray | Vitamin C',
    price: 96000,
    old_price: 108000,
    discount: '11%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-xit-ngan-mui-nu-nivea-sang-da-mo-vet-tham-150ml_ukGPTHpWUvrDD5hh_img_380x380_64adc6_fit_center.png',
    rating: 4.85,
    rates: 142,
    products_sold: '170',
  },
  {
    _id: '422208223',
    name: 'Kem Tẩy Lông Viền Bikini Cléo Từ Khoai Tây & Mật Ong 50g',
    category: 'Chăm Sóc Cơ Thể / Tẩy Lông / Triệt Lông / Kem Tẩy Lông',
    brand: 'VASELINE',
    desc_vn: 'Combo Serum Dưỡng Thể Vaseline Chống Nắng Sáng Da 300mlx2',
    desc_eng:
      'Healthy Bright Daily Protection & Brightening Serum SPF 50+ PA++++',
    price: 295000,
    old_price: 406000,
    discount: '27%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-422209938-1689242744_img_380x380_64adc6_fit_center.jpg',
    rating: 4.95,
    rates: 141,
    products_sold: '55',
  },
  {
    _id: '422201055',
    name: 'Kem Dưỡng Thể Paula’s Choice 10% AHA Làm Sáng Da 210ml',
    category: 'Chăm Sóc Cơ Thể / Dưỡng Thể',
    brand: 'Cléo',
    desc_vn: 'Kem Tẩy Lông Viền Bikini Cléo Từ Khoai Tây & Mật Ong 50g',
    desc_eng: '',
    price: 98000,
    old_price: 132000,
    discount: '26%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-kem-tay-long-vien-bikini-cleo-tu-khoai-tay-mat-ong-50g-1659684540_img_380x380_64adc6_fit_center.jpg',
    rating: 4.74,
    rates: 35,
    products_sold: '163',
  },
  {
    _id: '309300015',
    name: 'Sữa Dưỡng Thể Cathy Doll Sáng Da 150ml',
    category: 'Chăm Sóc Cơ Thể / Dưỡng Thể',
    brand: "PAULA'S CHOICE",
    desc_vn: 'Kem Dưỡng Thể Paula’s Choice 10% AHA Làm Sáng Da 210ml',
    desc_eng: 'Resist Skin Revealing Body Lotion with 10% AHA',
    price: 649000,
    old_price: 950000,
    discount: '32%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-kem-duong-the-paula-s-choice-10-aha-lam-sang-da-210ml_6pfuGqxaxeCmb3cp_img_380x380_64adc6_fit_center.png',
    rating: 4.33,
    rates: 123,
    products_sold: '25',
  },
  {
    _id: '100190072',
    name: 'Sữa Tắm & Rửa Mặt La Roche-Posay Cho Da Khô Nhạy Cảm 200ml',
    category: 'Chăm Sóc Cơ Thể / Sữa Tắm',
    brand: 'Cathy Doll',
    desc_vn: 'Sữa Dưỡng Thể Cathy Doll Sáng Da 150ml',
    desc_eng: 'Ready 2 White Whitener Body Lotion',
    price: 169000,
    old_price: 199000,
    discount: '15%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-sua-duong-the-trang-da-cathy-doll-150ml_rKamo8tfvqhLB4nF_img_380x380_64adc6_fit_center.png',
    rating: 4.41,
    rates: 61,
    products_sold: '93',
  },
  {
    _id: '100080005',
    name: 'Gel Khử Mùi Secret Giảm Tiết Mồ Hôi Hương Lavender 73g',
    category: 'Chăm Sóc Cơ Thể / Khử Mùi / Lăn Khử Mùi',
    brand: 'LA ROCHE-POSAY',
    desc_vn: 'Sữa Tắm & Rửa Mặt La Roche-Posay Cho Da Khô Nhạy Cảm 200ml',
    desc_eng: 'Lipikar Syndet AP+',
    price: 339000,
    old_price: 485000,
    discount: '30%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-sua-rua-mat-va-tam-la-roche-posay-danh-cho-da-kho-nhay-cam-da-bi-kich-ung-man-do-ngua-200ml-1672903340_img_380x380_64adc6_fit_center.jpg',
    rating: 4.01,
    rates: 65,
    products_sold: '46',
  },
  {
    _id: '422209262',
    name: 'Combo Cocoon Tẩy Da Chết Cho Mặt & Tẩy Da Chết Toàn Thân',
    category: 'Chăm Sóc Da Mặt / Bộ Chăm Sóc Da Mặt',
    brand: 'Secret',
    desc_vn: 'Gel Khử Mùi Secret Giảm Tiết Mồ Hôi Hương Lavender 73g',
    desc_eng: 'Clear Gel Deodorant #Lavender (Hàng Mỹ Nhập Khẩu Chính Hãng)',
    price: 114000,
    old_price: 125000,
    discount: '9%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-gel-khu-mui-secret-giam-tiet-mo-hoi-huong-lavender-73g_NKYKpqyUPYW7EM55_img_380x380_64adc6_fit_center.png',
    rating: 4.05,
    rates: 68,
    products_sold: '136',
  },
  {
    _id: '422210260',
    name: 'Sữa Dưỡng Thể Vaseline Bảo Vệ Sáng Mịn Ban Ngày 330ml',
    category: 'Chăm Sóc Cơ Thể / Dưỡng Thể',
    brand: 'Cocoon',
    desc_vn: 'Combo Cocoon Tẩy Da Chết Cho Mặt & Tẩy Da Chết Toàn Thân',
    desc_eng: 'Dak Lak Coffee Body Polish 200ml + Face Polish 150ml',
    price: 165000,
    old_price: 260000,
    discount: '37%',
    image:
      'https://media.hasaki.vn/catalog/product/t/o/top_fb_ads_422209262_240723-1690185366_img_380x380_64adc6_fit_center.jpg',
    rating: 4.43,
    rates: 37,
    products_sold: '94',
  },
  {
    _id: '422208939',
    name: 'Sữa Tắm Double Rich Hoa Iris Huyền Bí Dreamy Romance 800g',
    category: 'Chăm Sóc Cơ Thể / Sữa Tắm',
    brand: 'VASELINE',
    desc_vn: 'Sữa Dưỡng Thể Vaseline Bảo Vệ Sáng Mịn Ban Ngày 330ml',
    desc_eng: 'Gluta-Hya Serum Burst UV Lotion Flawless Bright',
    price: 115000,
    old_price: 150000,
    discount: '23%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-422210260-1689241451_img_380x380_64adc6_fit_center.jpg',
    rating: 4.83,
    rates: 138,
    products_sold: '126',
  },
  {
    _id: '422209540',
    name: 'Dung Dịch Vệ Sinh Nam Giới Nerman - Sanda Perfume 100ml',
    category: 'Chăm Sóc Cơ Thể / Sữa Tắm',
    brand: 'DOUBLE RICH',
    desc_vn: 'Sữa Tắm Double Rich Hoa Iris Huyền Bí Dreamy Romance 800g',
    desc_eng: 'Body Shower - Dreamy Romance',
    price: 115000,
    old_price: 151000,
    discount: '24%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-sua-tam-double-rich-hoa-iris-huyen-bi-dreamy-romance-800g_f9vvC4ErnRg3dmCQ_img_380x380_64adc6_fit_center.png',
    rating: 4.59,
    rates: 114,
    products_sold: '124',
  },
  {
    _id: '242300005',
    name: 'Lăn Khử Mùi EtiaXil Hàng Ngày Cho Mọi Loại Da 50ml',
    category: 'Chăm Sóc Cơ Thể / Khử Mùi / Lăn Khử Mùi',
    brand: 'Nerman',
    desc_vn: 'Dung Dịch Vệ Sinh Nam Giới Nerman - Sanda Perfume 100ml',
    desc_eng: 'Elegant Men Intimate Wash',
    price: 97000,
    old_price: 109000,
    discount: '11%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-dung-dich-ve-sinh-nam-gioi-nerman-sanda-perfume-100ml_HzNyCwvbwW7VZAgP_img_380x380_64adc6_fit_center.png',
    rating: 4.48,
    rates: 124,
    products_sold: '146',
  },
  {
    _id: '422200357',
    name: 'Serum Ngăn Mùi Dove Giúp Mờ Thâm Thu Nhỏ Lỗ Chân Lông 40ml',
    category: 'Chăm Sóc Cơ Thể / Khử Mùi / Lăn Khử Mùi',
    brand: 'EtiaXil',
    desc_vn: 'Lăn Khử Mùi EtiaXil Hàng Ngày Cho Mọi Loại Da 50ml',
    desc_eng: 'Anti-Perspirant Deodorant 48h Roll-On',
    price: 209000,
    old_price: 249000,
    discount: '16%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-lan-khu-mui-etiaxil-hang-ngay-cho-moi-loai-da-50ml-1643096251_img_380x380_64adc6_fit_center.jpg',
    rating: 4.45,
    rates: 40,
    products_sold: '66',
  },
  {
    _id: '379000002',
    name: 'Sữa Tắm Love Beauty And Planet Sáng Da Rạng Rỡ 400ml',
    category: 'Chăm Sóc Cơ Thể / Sữa Tắm',
    brand: 'Dove',
    desc_vn: 'Serum Ngăn Mùi Dove Giúp Mờ Thâm Thu Nhỏ Lỗ Chân Lông 40ml',
    desc_eng: 'Deodorant Dry Serum 3% Niacinamide + 10X Vit C&E',
    price: 67000,
    old_price: 97000,
    discount: '31%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-serum-ngan-mui-dove-giup-mo-tham-thu-nho-lo-chan-long-40ml-1687860325_img_380x380_64adc6_fit_center.jpg',
    rating: 4.88,
    rates: 105,
    products_sold: '203',
  },
  {
    _id: '422206631',
    name: 'Sữa Dưỡng Thể Hatomugi Chống Nắng Nâng Tông SPF31 PA+++ 250ml',
    category: 'Chăm Sóc Cơ Thể / Dưỡng Thể',
    brand: 'Love Beauty And Planet',
    desc_vn: 'Sữa Tắm Love Beauty And Planet Sáng Da Rạng Rỡ 400ml',
    desc_eng: 'Majectic Glow Body Wash',
    price: 167000,
    old_price: 189000,
    discount: '12%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-sua-tam-love-beauty-and-planet-lam-sang-da-400ml-1676689328_img_380x380_64adc6_fit_center.jpg',
    rating: 4.95,
    rates: 129,
    products_sold: '80',
  },
  {
    _id: '422207326',
    name: 'Sữa Tắm Lifebuoy Detox Than Hoạt Tính & Cám Gạo 800g',
    category: 'Chăm Sóc Cơ Thể / Sữa Tắm',
    brand: 'HATOMUGI',
    desc_vn: 'Sữa Dưỡng Thể Hatomugi Chống Nắng Nâng Tông SPF31 PA+++ 250ml',
    desc_eng: 'The Tone Up UV Milky Gel UV Care & Tone Up',
    price: 173000,
    old_price: 200000,
    discount: '13%',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-sua-duong-the-hatomugi-nang-tong-da-chong-nang-250ml-1642755511_img_380x380_64adc6_fit_center.jpg',
    rating: 4.32,
    rates: 51,
    products_sold: '77',
  },
  {
    _id: '422205685',
    name: 'Sữa Dưỡng Thể Vaseline Dưỡng Sáng Da 5% Niacinamide 250ml',
    category: 'Chăm Sóc Cơ Thể / Dưỡng Thể',
    brand: 'Lifebuoy',
    desc_vn: 'Sữa Tắm Lifebuoy Detox Than Hoạt Tính & Cám Gạo 800g',
    desc_eng: '',
    price: 161000,
    old_price: 195000,
    discount: '17%',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-sua-tam-lifebuoy-detox-than-hoat-tinh-cam-gao-800g-1682064092_img_380x380_64adc6_fit_center.jpg',
    rating: 4.73,
    rates: 33,
    products_sold: '82',
  },
  {
    _id: '422204625',
    name: 'Sữa Tắm St.Ives Tẩy Tế Bào Chết Hương Muối Biển 650ml',
    category: 'Chăm Sóc Cơ Thể / Sữa Tắm',
    brand: 'VASELINE',
    desc_vn: 'Sữa Dưỡng Thể Vaseline Dưỡng Sáng Da 5% Niacinamide 250ml',
    desc_eng: 'Pro Derma 3 - Niacinamide Brightening Body Lotion',
    price: 198000,
    old_price: 270000,
    discount: '27%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-422205685-1689320139_img_380x380_64adc6_fit_center.jpg',
    rating: 4.92,
    rates: 110,
    products_sold: '66',
  },
  {
    _id: '422205662',
    name: 'Sáp Khử Mùi Old Spice Giảm Tiết Mồ Hôi Hương Bearglove 73g',
    category: 'Chăm Sóc Cơ Thể / Khử Mùi / Sáp Khử Mùi',
    brand: 'ST.IVES',
    desc_vn: 'Sữa Tắm St.Ives Tẩy Tế Bào Chết Hương Muối Biển 650ml',
    desc_eng:
      'Sea Salt & Pacific Kelp Purifying Exfoliating Body Wash (New Packaging)',
    price: 152000,
    old_price: 180000,
    discount: '16%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-sua-tam-st-ives-chiet-xuat-muoi-bien-lam-sach-sau-650ml-1679386913_img_380x380_64adc6_fit_center.jpg',
    rating: 4.43,
    rates: 47,
    products_sold: '84',
  },
  {
    _id: '367400004',
    name: 'Kem Dưỡng Thể White Conc Làm Sáng Da Toàn Thân 200g',
    category: 'Chăm Sóc Cơ Thể / Dưỡng Thể',
    brand: 'Old Spice',
    desc_vn: 'Sáp Khử Mùi Old Spice Giảm Tiết Mồ Hôi Hương Bearglove 73g',
    desc_eng:
      'Bearglove Anti-Perspirant & Deodorant (Hàng Mỹ Nhập Khẩu Chính Hãng)',
    price: 122000,
    old_price: 154000,
    discount: '21%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-sap-khu-mui-old-spice-huong-bearglove-manh-me-ban-linh-73g_Yt54Fqd2FvLxBMoZ_img_380x380_64adc6_fit_center.png',
    rating: 4.92,
    rates: 138,
    products_sold: '105',
  },
  {
    _id: '248700051',
    name: 'Xịt Chống Nắng Naris Parasola Nâng Tông Da 80g',
    category: 'Chăm Sóc Da Mặt / Chống Nắng Da Mặt',
    brand: 'WHITE CONC',
    desc_vn: 'Kem Dưỡng Thể White Conc Làm Sáng Da Toàn Thân 200g',
    desc_eng: 'CC Cream',
    price: 270000,
    old_price: 350000,
    discount: '23%',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-kem-duong-the-white-conc-lam-sang-da-toan-than-200g-1686648734_img_380x380_64adc6_fit_center.jpg',
    rating: 4.63,
    rates: 133,
    products_sold: '46',
  },
  {
    _id: '422201794',
    name: 'Sữa Tắm Double Rich Dưỡng Ẩm Da Hương Hoa Iris 550g',
    category: 'Chăm Sóc Cơ Thể / Sữa Tắm',
    brand: 'Naris Cosmetics',
    desc_vn: 'Xịt Chống Nắng Naris Parasola Nâng Tông Da 80g',
    desc_eng: 'Illumi Skin UV Spray SPF50+ PA++++',
    price: 321000,
    old_price: 495000,
    discount: '35%',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-xit-chong-nang-naris-cosmetics-nang-tone-spf50-pa-80g-1682585526_img_380x380_64adc6_fit_center.jpg',
    rating: 4.71,
    rates: 134,
    products_sold: '39',
  },
  {
    _id: '422206728',
    name: 'Kem Dưỡng Thể Sur.Medic+ Sáng Da & Nâng Tông 150ml',
    category: 'Chăm Sóc Cơ Thể / Dưỡng Thể',
    brand: 'DOUBLE RICH',
    desc_vn: 'Sữa Tắm Double Rich Dưỡng Ẩm Da Hương Hoa Iris 550g',
    desc_eng: 'Body Shower Dreamy Romance',
    price: 72000,
    old_price: 99000,
    discount: '27%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-sua-tam-double-rich-duong-am-da-huong-hoa-iris-550g_nrH7WzZ61KTBgt3i_img_380x380_64adc6_fit_center.png',
    rating: 4.89,
    rates: 90,
    products_sold: '169',
  },
  {
    _id: '422202031',
    name: 'Xịt Khử Mùi Dove Dưỡng Da Sáng Mịn Hương Phấn Thơm 150ml',
    category: 'Chăm Sóc Cơ Thể / Khử Mùi / Xịt Khử Mùi',
    brand: 'SUR-MEDIC+',
    desc_vn: 'Kem Dưỡng Thể Sur.Medic+ Sáng Da & Nâng Tông 150ml',
    desc_eng: 'Super Glutathione 100TM Bright Body Tone Up Cream',
    price: 348000,
    old_price: 499000,
    discount: '30%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-kem-duong-the-sur-medic-sang-da-nang-tong-150ml_UEfCXaL57TXPpnj2_img_380x380_64adc6_fit_center.png',
    rating: 4.71,
    rates: 118,
    products_sold: '35',
  },
  {
    _id: '248700114',
    name: 'Xịt Chống Nắng Naris Parasola UV SPF50+ PA++++ 50g',
    category: 'Chăm Sóc Da Mặt / Chống Nắng Da Mặt',
    brand: 'Dove',
    desc_vn: 'Xịt Khử Mùi Dove Dưỡng Da Sáng Mịn Hương Phấn Thơm 150ml',
    desc_eng: 'Powder Soft Warm Powder Scent Anti-perspirant',
    price: 99000,
    old_price: 125000,
    discount: '21%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-xit-khu-mui-dove-duong-da-sang-min-huong-phan-thom-150ml-1677303478_img_380x380_64adc6_fit_center.jpg',
    rating: 4.72,
    rates: 112,
    products_sold: '122',
  },
  {
    _id: '422205048',
    name: 'Sữa Tắm Happy Bath Chiết Xuất Từ Nước Gạo Thiên Nhiên 900g',
    category: 'Chăm Sóc Cơ Thể / Sữa Tắm',
    brand: 'Naris Cosmetics',
    desc_vn: 'Xịt Chống Nắng Naris Parasola UV SPF50+ PA++++ 50g',
    desc_eng: 'Parasola Fragrance UV Cut Spray',
    price: 191000,
    old_price: 295000,
    discount: '35%',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-xit-chong-nang-naris-parasola-uv-spf50-pa-50g-1650642359_img_380x380_64adc6_fit_center.jpg',
    rating: 4.07,
    rates: 66,
    products_sold: '63',
  },
  {
    _id: '422206189',
    name: 'Sữa Dưỡng Thể Cathy Doll Dưỡng Sáng, Mờ Thâm 450ml',
    category: 'Chăm Sóc Cơ Thể / Dưỡng Thể',
    brand: 'HAPPY BATH',
    desc_vn: 'Sữa Tắm Happy Bath Chiết Xuất Từ Nước Gạo Thiên Nhiên 900g',
    desc_eng: 'Real Mild Natural Body Wash',
    price: 129000,
    old_price: 200000,
    discount: '35%',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-sua-tam-happy-bath-chiet-xuat-tu-nuoc-gao-thien-nhien-900g_img_380x380_64adc6_fit_center.jpg',
    rating: 4.84,
    rates: 100,
    products_sold: '93',
  },
  {
    _id: '422209541',
    name: 'Sữa Tắm Gội Nerman Hương Nước Hoa Cao Cấp 350ml',
    category: 'Chăm Sóc Cơ Thể / Sữa Tắm',
    brand: 'Cathy Doll',
    desc_vn: 'Sữa Dưỡng Thể Cathy Doll Dưỡng Sáng, Mờ Thâm 450ml',
    desc_eng: 'Whitamin Vitamin C Arbutin Body Lotion',
    price: 135000,
    old_price: 159000,
    discount: '15%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-sua-duong-the-cathy-doll-duong-sang-mo-tham-450ml_vCrUhQbBLQpe9PkH_img_380x380_64adc6_fit_center.png',
    rating: 4.87,
    rates: 109,
    products_sold: '87',
  },
  {
    _id: '213300030',
    name: 'Serum Chống Nắng Dưỡng Thể Bioré Sáng Mịn Mát Lạnh 50ml',
    category: 'Chăm Sóc Cơ Thể / Chống Nắng Cơ Thể',
    brand: 'Nerman',
    desc_vn: 'Sữa Tắm Gội Nerman Hương Nước Hoa Cao Cấp 350ml',
    desc_eng: 'Gentleman 3in1 Body, Face and Hair Wash',
    price: 187000,
    old_price: 209000,
    discount: '11%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-sua-tam-goi-nerman-huong-nuoc-hoa-cao-cap-350ml_xy4hdXfJKWFJTbDi_img_380x380_64adc6_fit_center.png',
    rating: 4.96,
    rates: 111,
    products_sold: '62',
  },
  {
    _id: '100180196',
    name: 'Sữa Dưỡng Thể St.Ives Yến Mạch & Bơ Dưỡng Ẩm Dịu Da 621ml',
    category: 'Chăm Sóc Cơ Thể / Dưỡng Thể',
    brand: 'Bioré',
    desc_vn: 'Serum Chống Nắng Dưỡng Thể Bioré Sáng Mịn Mát Lạnh 50ml',
    desc_eng: 'UV Anti-Pollution Body Care Serum Refresh Bright SPF 50+/PA+++',
    price: 70000,
    old_price: 79000,
    discount: '11%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-serum-chong-nang-duong-the-biore-khang-bui-sang-min-mat-lanh-spf-50-pa-50ml-1688462354_img_380x380_64adc6_fit_center.jpg',
    rating: 4.43,
    rates: 118,
    products_sold: '162',
  },
  {
    _id: '422209660',
    name: 'Bộ Sữa Tắm Và Dưỡng Thể De Memoria Hương Jasmine On Moon 2x300ml',
    category: 'Chăm Sóc Cơ Thể / Bộ Chăm Sóc Cơ Thể',
    brand: 'ST.IVES',
    desc_vn: 'Sữa Dưỡng Thể St.Ives Yến Mạch & Bơ Dưỡng Ẩm Dịu Da 621ml',
    desc_eng: 'Nourish & Soothe Oatmeal & Shea Butter Body Lotion',
    price: 159000,
    old_price: 192000,
    discount: '17%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-sua-duong-the-st-ives-yen-mach-bo-duong-am-diu-da-621ml-1669953391_img_380x380_64adc6_fit_center.jpg',
    rating: 4.63,
    rates: 132,
    products_sold: '70',
  },
  {
    _id: '422207893',
    name: 'Gel Rửa Mặt SVR Không Xà Phòng Cho Da Khô, Nhạy Cảm 200ml',
    category: 'Chăm Sóc Da Mặt / Làm Sạch Da / Sữa Rửa Mặt',
    brand: 'De Memoria',
    desc_vn: 'Bộ Sữa Tắm Và Dưỡng Thể De Memoria Hương Jasmine On Moon 2x300ml',
    desc_eng: 'Scented W​hitening B​ody Cleanser And Lotion #Jasmine On Moon',
    price: 501000,
    old_price: 1100000,
    discount: '54%',
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-bo-sua-tam-va-duong-the-de-memoria-huong-jasmine-on-moon-2x300ml-1665134175_img_380x380_64adc6_fit_center.jpg',
    rating: 4.67,
    rates: 128,
    products_sold: '22',
  },
  {
    _id: '422211152',
    name: 'Combo 2 Sữa Dưỡng Thể Vaseline Sáng Da Chuyên Sâu Ban Đêm 330ml',
    category: 'Chăm Sóc Cơ Thể / Dưỡng Thể',
    brand: 'SVR',
    desc_vn: 'Gel Rửa Mặt SVR Không Xà Phòng Cho Da Khô, Nhạy Cảm 200ml',
    desc_eng: 'Topialyse Gel Lavant',
    price: 277000,
    old_price: 320000,
    discount: '13%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-gel-rua-mat-svr-lam-sach-da-khong-chua-xa-phong-200ml_GwcvWXSFojFvEr2V_img_380x380_64adc6_fit_center.png',
    rating: 4.55,
    rates: 143,
    products_sold: '38',
  },
  {
    _id: '422201212',
    name: 'Muối Tắm BareSoul Tẩy Tế Bào Chết Cho Da Đầu & Cơ Thể 330g',
    category: 'Chăm Sóc Tóc Và Da Đầu / Tẩy Tế Bào Chết Da Đầu',
    brand: 'VASELINE',
    desc_vn: 'Combo 2 Sữa Dưỡng Thể Vaseline Sáng Da Chuyên Sâu Ban Đêm 330ml',
    desc_eng: 'Gluta-Hya Serum Burst UV Lotion Dewy Radiance',
    price: 237000,
    old_price: 300000,
    discount: '21%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-422211152-1689240954_img_380x380_64adc6_fit_center.jpg',
    rating: 4.62,
    rates: 70,
    products_sold: '45',
  },
  {
    _id: '223000004',
    name: 'Sữa Tắm Gội Coast Dành Cho Nam 946ml',
    category: 'Chăm Sóc Cơ Thể / Sữa Tắm',
    brand: 'BareSoul',
    desc_vn: 'Muối Tắm BareSoul Tẩy Tế Bào Chết Cho Da Đầu & Cơ Thể 330g',
    desc_eng: 'Free Body & Hair Scrub',
    price: 195000,
    old_price: 250000,
    discount: '22%',
    image:
      'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-422201212-1689582113_img_380x380_64adc6_fit_center.png',
    rating: 4.19,
    rates: 31,
    products_sold: '53',
  },
  {
    _id: '207600002',
    name: 'Gel Khử Mùi Secret Giảm Tiết Mồ Hôi Protecting Powder 73g',
    category: 'Chăm Sóc Cơ Thể / Khử Mùi / Lăn Khử Mùi',
    brand: 'Coast',
    desc_vn: 'Sữa Tắm Gội Coast Dành Cho Nam 946ml',
    desc_eng: 'Classic Scent Hair & Body Wash',
    price: 183000,
    old_price: null,
    discount: null,
    image:
      'https://media.hasaki.vn/catalog/product/g/o/google-shopping-sua-tam-goi-danh-cho-nam-coast-946ml-1_img_380x380_64adc6_fit_center.jpg',
    rating: 4.99,
    rates: 83,
    products_sold: '56',
  },
  {
    _id: '206200069',
    name: 'Lăn Khử Mùi Nivea Serum Sáng Mịn Hương Hoa Sakura 40ml',
    category: 'Chăm Sóc Cơ Thể / Khử Mùi / Lăn Khử Mùi',
    brand: 'Secret',
    desc_vn: 'Gel Khử Mùi Secret Giảm Tiết Mồ Hôi Protecting Powder 73g',
    desc_eng: 'Outlast Clear Gel Deodorant #Protecting Powder',
    price: 114000,
    old_price: 125000,
    discount: '9%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-gel-khu-mui-secret-giam-tiet-mo-hoi-protecting-powder-73g_GuLKcs1FiLgaQwoj_img_380x380_64adc6_fit_center.png',
    rating: 4.51,
    rates: 57,
    products_sold: '90',
  },
  {
    _id: '206200072',
    name: 'Xịt Khử Mùi Nivea Ngọc Trai Dưỡng Da Sáng Mịn 150ml',
    category: 'Chăm Sóc Cơ Thể / Khử Mùi / Xịt Khử Mùi',
    brand: 'NIVEA',
    desc_vn: 'Lăn Khử Mùi Nivea Serum Sáng Mịn Hương Hoa Sakura 40ml',
    desc_eng: 'Brightening Deep Serum Bright & Firm Sakura',
    price: 96000,
    old_price: 108000,
    discount: '11%',
    image:
      'https://media.hasaki.vn/catalog/product/p/r/promotions-auto-lan-ngan-mui-nivea-serum-sang-min-huong-hoa-sakura-40ml_CGE65PfzxFvD8Puq_img_380x380_64adc6_fit_center.png',
    rating: 4.24,
    rates: 75,
    products_sold: '104',
  },
];

export default products;
